name: Prepare storage for build artifacts
description: This snippet prepares storage and creates required directories for artifacts.

inputs:
  ssh_host:
    required: true
  ssh_port:
    required: true
  ssh_user:
    required: true
  ssh_key:
    required: true
  storage_prefix:
    required: true
  directory:
    required: true

runs:
  using: "composite"
  steps:
    - name: Prepare storage
      id: prepare-storage
      run: |
        eval $(ssh-agent -s)
        echo "${{ inputs.ssh_key }}" | ssh-add -
        mkdir -p ~/.ssh && echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
        mkdir -p ./dists/
        ssh -p ${{ inputs.ssh_port }} ${{ inputs.ssh_user }}@${{ inputs.ssh_host }} -- "mkdir -p ${{ inputs.storage_prefix }}/${{ inputs.directory }}"
