name: Build KS:RE

on:
  workflow_dispatch:
  push:

env:
  SDL_AUDIODRIVER: dummy
  SDL_VIDEODRIVER: dummy
  RENPY_VERSION: 8.5.3

concurrency:
  group: ${{ forge.workflow-ref }}-build
  cancel-in-progress: true

jobs:
  build:
    runs-on: renkit
    name: Build KS:RE release

    steps:
      - name: Checkout the code
        id: checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
      
      - uses: ./.forgejo/actions/semver
        id: semver
