name: Build KS:RE

on:
  workflow_dispatch:
  push:

env:
  SDL_AUDIODRIVER: dummy
  SDL_VIDEODRIVER: dummy
  RENPY_VERSION: 8.5.3

concurrency:
  group: ${{ forge.workflow-ref }}-build
  cancel-in-progress: true

jobs:
  build:
    runs-on: renkit-amd64
    name: Build KS:RE release

    steps:
      - name: Checkout the code
        id: checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
      
      - name: Determine current game version
        uses: ./.forgejo/actions/semver
        id: semver

      - name: Prepare storage for build artifacts
        uses: ./.forgejo/actions/prepare-storage
        id: prepare-storage
        with:
          ssh_host: ${{ secrets.STORAGE_SSH_HOST }}
          ssh_port: ${{ secrets.STORAGE_SSH_PORT }}
          ssh_user: ${{ secrets.STORAGE_SSH_USER }}
          ssh_key: ${{ secrets.STORAGE_SSH_KEY }}
          storage_prefix: ${{ secrets.STORAGE_DIRECTORY_PREFIX }}
          directory: ${{ steps.semver.outputs.CI_PRETTY_VERSION }}

      - name: Build the game
        id: build
        run: |
          sed -i "s#0.0.0-localbuild#${{ steps.semver.outputs.CI_KSRE_VERSION }}#" game/config.rpy
          sed -i "s#KEYSTORE_APK#${KEYSTORE_APK}#" renconstruct/release.toml
          sed -i "s#KEYSTORE_PASS#${KEYSTORE_PASS}#" renconstruct/release.toml
          sed -i "s#RENPY_VERSION#${RENPY_VERSION}#" renconstruct/release.toml
          renconstruct build -c renconstruct/release.toml . ./dists
        env:
          KEYSTORE_APK: ${{ secrets.KEYSTORE_APK }}
          KEYSTORE_PASS: ${{ secrets.KEYSTORE_PASS }}

      - name: Upload build artifacts to storage
        uses: ./.forgejo/actions/upload-file
        id: upload-artifact
        with:
          ssh_host: ${{ secrets.STORAGE_SSH_HOST }}
          ssh_port: ${{ secrets.STORAGE_SSH_PORT }}
          ssh_user: ${{ secrets.STORAGE_SSH_USER }}
          ssh_key: ${{ secrets.STORAGE_SSH_KEY }}
          storage_prefix: ${{ secrets.STORAGE_DIRECTORY_PREFIX }}
          directory: ${{ steps.semver.outputs.CI_PRETTY_VERSION }}
          artifact_name: "*"
