name: Build KS:RE

on:
  workflow_dispatch:
  push:

env:
  SDL_AUDIODRIVER: dummy
  SDL_VIDEODRIVER: dummy
  RENPY_VERSION: 8.5.3

concurrency:
  group: ${{ forge.workflow-ref }}-build
  cancel-in-progress: true

jobs:
  build:
    runs-on: renkit
    name: Build KS:RE release

    steps:
      - name: Checkout the code
        id: checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
      
      - name: Determine current game version
        uses: ./.forgejo/actions/semver
        id: semver

      - name: Prepare storage for build artifacts
        uses: ./.forgejo/actions/prepare-storage
        id: prepare-storage
        with:
          ssh_host: ${{ secrets.STORAGE_SSH_HOST }}
          ssh_port: ${{ secrets.STORAGE_SSH_PORT }}
          ssh_user: ${{ secrets.STORAGE_SSH_USER }}
          ssh_key: ${{ secrets.STORAGE_SSH_KEY }}
          storage_prefix: ${{ secrets.STORAGE_DIRECTORY_PREFIX }}
          directory: ${{ steps.semver.outputs.CI_PRETTY_VERSION }}
