name: Lint Ren'Py code

on:
  workflow_dispatch:
  push:

env:
  SDL_AUDIODRIVER: dummy
  SDL_VIDEODRIVER: dummy
  RENPY_VERSION: 8.5.3

concurrency:
  group: ${{ forge.workflow-ref }}-lint
  cancel-in-progress: true

jobs:
  lint:
    runs-on: renkit
    name: Lint Ren'Py code

    steps:
      - name: Checkout the code
        id: checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
      
      - name: Determine used version
        id: semver
        run: |
          case "${FORGEJO_REF}" in
              refs/tags/*)
                  TAG="${FORGEJO_REF#refs/tags/}"
                  VERSION="${TAG}"
                  GAME_VERSION="${TAG#v}"
                  ;;
              *)
                  PREVIOUS_TAG="$(git -c 'versionsort.suffix=-' \
                                    tag --list 'v*.*.*' --sort=-v:refname | head -n 1)"
                  PREVIOUS_TAG="${PREVIOUS_TAG:-v0.0.0}"

                  BASE="${PREVIOUS_TAG#v}"
                  BASE="${BASE%%-*}"
                  IFS=. read -r MAJOR MINOR PATCH <<< "${BASE}"
                  PATCH=$((PATCH + 1))

                  VERSION="v${MAJOR}.${MINOR}.${PATCH}-${FORGEJO_SHA:0:10}"
                  GAME_VERSION="${MAJOR}.${MINOR}.${PATCH}-${FORGEJO_SHA:0:4}"
                  ;;
          esac

          echo "CI_PRETTY_VERSION=${VERSION}" | tee -a "${FORGEJO_OUTPUT}"
          echo "CI_KSRE_VERSION=${GAME_VERSION}" | tee -a "${FORGEJO_OUTPUT}"

      - name: Lint Ren'Py code
        id: lint
        run: |
          echo "CI_KSRE_VERSION=${{ steps.semver.outputs.CI_PRETTY_VERSION }}"
          renutil launch -v ${RENPY_VERSION} -d . -- lint --error-code --no-orphan-tl
        continue-on-error: true
