# TODO: Translation updated at 2025-12-19 01:29
# Generated by Renquill

translate pt_br strings:

    # renpy/common/000statements.rpy:28
    old "Click to play the video."
    new "Clique para reproduzir o vídeo."

    # renpy/common/00accessibility.rpy:28
    old "Self-voicing disabled."
    new "Auto-voz desativada."

    # renpy/common/00accessibility.rpy:29
    old "Clipboard voicing enabled. "
    new "Voz da área de transferência ativada."

    # renpy/common/00accessibility.rpy:30
    old "Self-voicing enabled. "
    new "Auto-voz ativada."

    # renpy/common/00accessibility.rpy:32
    old "bar"
    new "barra"

    # renpy/common/00accessibility.rpy:33
    old "selected"
    new "selecionado"

    # renpy/common/00accessibility.rpy:34
    old "viewport"
    new "visualização"

    # renpy/common/00accessibility.rpy:35
    old "horizontal scroll"
    new "rolagem horizontal"

    # renpy/common/00accessibility.rpy:36
    old "vertical scroll"
    new "rolagem vertical"

    # renpy/common/00accessibility.rpy:37
    old "activate"
    new "ativar"

    # renpy/common/00accessibility.rpy:38
    old "deactivate"
    new "desativar"

    # renpy/common/00accessibility.rpy:39
    old "increase"
    new "aumentar"

    # renpy/common/00accessibility.rpy:40
    old "decrease"
    new "diminuir"

    # renpy/common/00accessibility.rpy:134
    old "Self-Voicing"
    new "Auto-Voz"

    # renpy/common/00accessibility.rpy:137
    old "Self-voicing support is limited when using a touch screen."
    new "Auto-Voz será limitado utilizando uma tela touch screen."

    # renpy/common/00accessibility.rpy:139
    old "Off"
    new "Desligado"

    # renpy/common/00accessibility.rpy:143
    old "Text-to-speech"
    new "Síntese de fala"

    # renpy/common/00accessibility.rpy:147
    old "Clipboard"
    new "Área de transferência"

    # renpy/common/00accessibility.rpy:151
    old "Debug"
    new "Depuar"

    # renpy/common/00accessibility.rpy:155
    old "Voice Volume"
    new "Volume de Voz"

    # renpy/common/00accessibility.rpy:163
    old "Reset"
    new "Resetar"

    # renpy/common/00accessibility.rpy:167
    old "Self-Voicing Volume Drop"
    new "Abaixar a Auto-Voz"

    # renpy/common/00accessibility.rpy:180
    old "Mono Audio"
    new "Aúdio Mono"

    # renpy/common/00accessibility.rpy:186
    old "Disable"
    new "Desativar"

    # renpy/common/00accessibility.rpy:198
    old "Font Override"
    new "Substituição de fonte"

    # renpy/common/00accessibility.rpy:204
    old "DejaVu Sans"
    new "DejaVu Sans"



    # renpy/common/00accessibility.rpy:208
    old "Opendyslexic"
    new "Opendyslexic"



    # renpy/common/00accessibility.rpy:212
    old "High Contrast Text"
    new "High Contrast Text"



    # renpy/common/00accessibility.rpy:224
    old "Text Size Scaling"
    new "Tamanho do Texto"

    # renpy/common/00accessibility.rpy:235
    old "Line Spacing Scaling"
    new "Espaçamento de linha"

    # renpy/common/00accessibility.rpy:246
    old "Kerning"
    new "Kerning"



    # renpy/common/00accessibility.rpy:267
    old "Accessibility Menu. Use up and down arrows to navigate, and enter to activate buttons and bars."
    new "Menu de acessibilidade. Use as setas para cima e para baixo para navegar e pressione Enter para interagir com os botões e barras."


    # renpy/common/00accessibility.rpy:288
    old "Self-Voicing and Audio"
    new "Auto-Voz e Aúdio"

    # renpy/common/00accessibility.rpy:292
    old "Text"
    new "Texto"

    # renpy/common/00accessibility.rpy:306
    old "The options on this menu are intended to improve accessibility. They may not work with all games, and some combinations of options may render the game unplayable. This is not an issue with the game or engine. For the best results when changing fonts, try to keep the text size the same as it originally was."
    new "As opções deste menu têm como objetivo melhorar a acessibilidade. Elas podem não funcionar com todos os jogos, e algumas combinações de opções podem tornar o jogo impossível de jogar. Isso não é um problema do jogo ou da engine. Para obter melhores resultados ao alterar as fontes, tente manter o tamanho do texto igual ao original."

    # renpy/common/00gui.rpy:448
    old "Are you sure?"
    new "Tem certeza?"

    # renpy/common/00gui.rpy:449
    old "Are you sure you want to delete this save?"
    new "Tem certeza de que deseja excluir este arquivo?"


    # renpy/common/00gui.rpy:450
    old "Are you sure you want to overwrite your save?"
    new "Tem certeza de que deseja substituir seu arquivo?"



    # renpy/common/00gui.rpy:451
    old "Loading will lose unsaved progress.\nAre you sure you want to do this?"
    new "O carregamento perderá o progresso não salvo. Tem certeza de que deseja fazer isso?"

    # renpy/common/00gui.rpy:452
    old "Are you sure you want to quit?"
    new "Tem certeza de que deseja sair?"


    # renpy/common/00gui.rpy:453
    old "Are you sure you want to return to the main menu?\nThis will lose unsaved progress."
    new "Tem certeza de que deseja retornar ao menu principal?\nIsso fará com que o progresso não salvo seja perdido."


    # renpy/common/00gui.rpy:454
    old "Are you sure you want to continue where you left off?"
    new "Tem certeza de que deseja continuar de onde parou?"

    # renpy/common/00gui.rpy:455
    old "Are you sure you want to end the replay?"
    new "Tem certeza de que deseja encerrar o replay?"

    # renpy/common/00keymap.rpy:346
    old "Saved screenshot as %s."
    new "Captura de tela salva como %s."

