# TODO: Translation updated at 2025-12-18 03:29
# Generated by Renquill

translate pt_br strings:

    # game/definitions.rpy:119
    old " (replay)"
    new " (replay)"

    # game/definitions.rpy:121
    old "No scene"
    new "Sem cena"

    # game/definitions.rpy:126
    old "Nothing"
    new "Nenhuma"

    # game/definitions.rpy:175
    old "Playing history"
    new "No histórico"

    # game/definitions.rpy:176
    old "Watching video"
    new "Assistindo vídeo"

    # game/definitions.rpy:179
    old "In main menu"
    new "No menu principal"

    # game/definitions.rpy:180
    old "Listening"
    new "Ouvindo"

    # game/definitions.rpy:224
    old "Act 1"
    new "Ato 1"

    # game/definitions.rpy:224
    old "Prologue"
    new "Prólogo"

    # game/definitions.rpy:224
    old "Out Cold"
    new "No Chão Frio"

    # game/definitions.rpy:224
    old "On a cold, snowy day, Hisao's dreams were about to be realized, only to be cut short by a sudden heart attack."
    new "Em um dia frio e com neve, os sonhos de Hisao estavam prestes a se realizar, mas foram interrompidos por um súbito ataque cardíaco."

    # game/definitions.rpy:224
    old "Bundle of Hisao"
    new "Feixe de Hisao"

    # game/definitions.rpy:224
    old "Hisao is told about Yamaku Academy, where he will likely spend the rest of his high school days."
    new "Hisao é informado sobre a Academia Yamaku, onde ele passará provavelmente o resto dos seus dias de escola."

    # game/definitions.rpy:224
    old "Act 1: Life Expectancy"
    new "Ato 1: Expectativa de Vida"

    # game/definitions.rpy:224
    old "Gateway Effect"
    new "Porta de Entrada"

    # game/definitions.rpy:224
    old "Hisao steps into Yamaku Academy for the first time, and meets his homeroom teacher, Mutou."
    new "Hisao entra na Academia Yamaku pela primeira vez e conhece o orientador da sua turma, Mutou."

    # game/definitions.rpy:224
    old "Enter Stage Left"
    new "Entrando Pelo Pé Esquerdo"

    # game/definitions.rpy:224
    old "Introductions to the class, and meeting with the class representative and her interpreter."
    new "Apresentações à sala e reunião com a representante da turma e sua intérprete."

    # game/definitions.rpy:224
    old "In the Nursery"
    new "Na Enfermaria"

    # game/definitions.rpy:224
    old "Misha and Shizune show Hisao the cafeteria, after which he goes to see the nurse."
    new "Misha e Shizune mostram Hisao a cantina, e depois ele vai ver o enfermeiro."

    # game/definitions.rpy:224
    old "Nobody's Room"
    new "Quarto de Ninguém"

    # game/definitions.rpy:224
    old "Hisao moves into his new room, meeting his hallmate Kenji in the process."
    new "Hisao se muda para seu novo quarto, conhecendo seu vizinho Kenji no processo."

    # game/definitions.rpy:224
    old "Smalltalk"
    new "Conversa Casual"

    # game/definitions.rpy:224
    old "Shizune and Misha tell Hisao about the upcoming festival and invite him to lunch."
    new "Shizune e Misha contam a Hisao sobre o próximo festival e o convidam para almoçar."

    # game/definitions.rpy:224
    old "Risk vs. Reward"
    new "Risco vs. Recompensa"

    # game/definitions.rpy:224
    old "Shizune and Hisao battle for the world in a game of Risk."
    new "Shizune e Hisao disputam o mundo em uma partida Risco."

    # game/definitions.rpy:224
    old "Pseudo Tea Cosy"
    new "Pseudo-Cobertor de Bule"

    # game/definitions.rpy:224
    old "Looking for the library, Hisao gets lost and finds Lilly in a disused classroom."
    new "Procurando a biblioteca, Hisao se perde e encontra Lilly em uma sala de aula sem uso."

    # game/definitions.rpy:224
    old "Shared Library"
    new "Biblioteca Compartilhada"

    # game/definitions.rpy:224
    old "Finally finding his way to the library, Hisao meets and scares off Hanako."
    new "Encontrando finalmente o caminho para a biblioteca, Hisao encontra e faz Hanako fugir."

    # game/definitions.rpy:224
    old "Bizarre and Surreal"
    new "Bizarro e Surreal"

    # game/definitions.rpy:224
    old "Kenji reveals the dark secrets of Yamaku."
    new "Kenji revela os segredos obscuros de Yamaku."

    # game/definitions.rpy:224
    old "Lunch Evolution Theory"
    new "Teoria da Evolução do Almoço"

    # game/definitions.rpy:224
    old "Shizune and Misha badger Hisao into joining the Student Council before discussing lunch."
    new "Shizune e Misha pressionam Hisao a entrar para o Conselho Estudantil antes de discutir o que terão no almoço."

    # game/definitions.rpy:224
    old "Short Sharp Shock"
    new "Choque Contundente Curto"

    # game/definitions.rpy:224
    old "On his way to lunch alongside Misha and Shizune, Hisao collides with Emi in the hallway."
    new "A caminho do almoço com Misha e Shizune, Hisao colide com Emi no corredor."

    # game/definitions.rpy:224
    old "Meet Cute"
    new "Primeiro Esbarrão"

    # game/definitions.rpy:224
    old "Hisao collides with a rampaging Emi on his way to lunch with Hanako and Lilly."
    new "Hisao colide com uma Emi desenfreada em seu caminho para o almoço com Hanako e Lilly."

    # game/definitions.rpy:224
    old "Detour Ahead"
    new "Desvio Adiante"

    # game/definitions.rpy:224
    old "Shizune and Misha take Hisao to their favourite teahouse, the Shanghai."
    new "Shizune e Misha levam Hisao para sua casa de chá favorita, o Xangai."

    # game/definitions.rpy:224
    old "Sip (Part 1)"
    new "Hora do Chá (Parte 1)"

    # game/definitions.rpy:224
    old "Hisao has a peaceful lunch with Lilly and Hanako."
    new "Hisao tem um almoço tranquilo com Lilly e Hanako."

    # game/definitions.rpy:224
    old "It Builds Character"
    new "Isso Constrói o Caráter."

    # game/definitions.rpy:224
    old "Mutou tries to have a D&M talk with Hisao, but Misha interrupts and puts Hisao to work."
    new "Mutou tenta ter uma conversa séria com Hisao, mas Misha interrompe e põe Hisao para trabalhar."

    # game/definitions.rpy:224
    old "A Private Lunch"
    new "Um Almoço Escondido"

    # game/definitions.rpy:224
    old "Searching for supplies, Hisao happens across a strange girl in the art room."
    new "Em busca de suprimentos, Hisao se depara com uma garota estranha na sala de artes."

    # game/definitions.rpy:224
    old "Waylay"
    new "Interceptado"

    # game/definitions.rpy:224
    old "While helping Rin carry some paint, Hisao is quizzed by the nurse."
    new "Enquanto ajuda Rin a carregar algumas tintas, Hisao é questionado pelo enfermeiro."

    # game/definitions.rpy:224
    old "The Other Green"
    new "O Outro Verde"

    # game/definitions.rpy:224
    old "Hisao watches Rin paint her mural."
    new "Hisao observa Rin pintar seu mural."

    # game/definitions.rpy:224
    old "The Running Girl"
    new "A Sobrevivente"

    # game/definitions.rpy:224
    old "When attempting to do some morning exercise, Hisao meets Emi at the running track."
    new "Na sua tentativa de fazer algum exercício matinal, Hisao encontra Emi na pista de atletismo."

    # game/definitions.rpy:224
    old "Soap"
    new "Sabão"

    # game/definitions.rpy:224
    old "Kenji ambushes Hisao in the shower in an attempt to get some cash."
    new "Kenji embosca Hisao no chuveiro em uma tentativa de conseguir algum dinheiro."

    # game/definitions.rpy:224
    old "Cold War"
    new "Guerra Fria"

    # game/definitions.rpy:224
    old "Shizune and Lilly face off over budget requests."
    new "Shizune e Lilly se desentendem sobre as solicitações de orçamento."

    # game/definitions.rpy:224
    old "Proof of Competency"
    new "Prova de Competência"

    # game/definitions.rpy:224
    old "Shizune and Misha assault Hisao in an attempt to get him to join the Student Council."
    new "Shizune e Misha atentam contra Hisao em uma tentativa de fazê-lo entrar para o Conselho Estudantil."

    # game/definitions.rpy:224
    old "Event Horizon"
    new "Ponto de Não Retorno"

    # game/definitions.rpy:224
    old "Above and Beyond"
    new "Para Cima e Além"

    # game/definitions.rpy:224
    old "Hisao gets a lecture about the noble duties of a Student Council."
    new "Hisao recebe uma palestra sobre os nobres deveres de um Conselho Estudantil."

    # game/definitions.rpy:224
    old "Paint by Numbers"
    new "Pintando Por Números"

    # game/definitions.rpy:224
    old "Hanako and Hisao lend a hand to Lilly's class by volunteering to help build their stall."
    new "Hanako e Hisao dão uma mãozinha para a turma de Lilly, oferecendo-se para ajudar a preparar a barraca deles."

    # game/definitions.rpy:224
    old "Things You Can Do"
    new "Coisas Que Você Pode Fazer"

    # game/definitions.rpy:224
    old "After escaping from the clutches of Shizune and Misha, Hisao helps out Rin again."
    new "Depois de escapar das garras de Shizune e Misha, Hisao ajuda Rin mais uma vez."

    # game/definitions.rpy:224
    old "Exercise"
    new "Exercício"

    # game/definitions.rpy:224
    old "Another early morning sees Hisao running at the track with Emi."
    new "Em outra manhã bem cedo, Hisao corre na pista com Emi."

    # game/definitions.rpy:224
    old "Invisible Hat"
    new "Chapéu Invisível"

    # game/definitions.rpy:224
    old "Kenji gives Hisao a few insider tips on how to socialize."
    new "Kenji dá a Hisao algumas dicas importantes sobre como se socializar."

    # game/definitions.rpy:224
    old "Home Field Advantage"
    new "Jogando em Casa"

    # game/definitions.rpy:224
    old "Shizune and Misha hijack Hisao as he leaves his room for class."
    new "Shizune e Misha capturam Hisao quando ele sai de seu quarto para a aula."

    # game/definitions.rpy:224
    old "No Recovery"
    new "Sem Resgate"

    # game/definitions.rpy:224
    old "Hisao struggles to class after his hijacking by the Student Council."
    new "Hisao luta para ir à aula após ter sido capturado pelo Conselho Estudantil."

    # game/definitions.rpy:224
    old "Slow Recovery"
    new "Recuperação Lenta"

    # game/definitions.rpy:224
    old "Recovering from his heart flutter, Hisao eventually makes it to class."
    new "Recuperando-se de sua agitação cardíaca, Hisao finalmente chega à aula."

    # game/definitions.rpy:224
    old "No Free Lunch"
    new "Sem Almoço Grátis"

    # game/definitions.rpy:224
    old "Hisao is escorted to the student council office for his first official day there."
    new "Hisao é escoltado até a sala do conselho estudantil para seu primeiro dia oficial lá."

    # game/definitions.rpy:224
    old "Foot and Mouth"
    new "Pés Pelas Mãos"

    # game/definitions.rpy:224
    old "Emi drags Hisao to the roof to have lunch with Rin."
    new "Emi arrasta Hisao para o telhado para almoçar com Rin."

    # game/definitions.rpy:224
    old "Mind Your Step"
    new "Cuidado Onde Pisa"

    # game/definitions.rpy:224
    old "Hisao and Lilly go shopping, meeting a very confused Rin on the way back."
    new "Hisao e Lilly vão às compras, encontrando uma Rin muito confusa no caminho de volta."

    # game/definitions.rpy:224
    old "Support"
    new "Apoio"

    # game/definitions.rpy:224
    old "Hisao has his first Saturday lesson, complete with a talking to from Mutou."
    new "Hisao tem sua primeira aula de sábado, completa com uma conversa com Mutou."

    # game/definitions.rpy:224
    old "An Aesthetics"
    new "Anestética"

    # game/definitions.rpy:224
    old "Emi finds Hisao slacking around after class and recruits him to help Rin once again."
    new "Emi descobre que Hisao está relaxando depois da aula e o recruta para ajudar Rin mais uma vez."

    # game/definitions.rpy:224
    old "Creative Pain"
    new "Dor Criativa"

    # game/definitions.rpy:224
    old "Hisao meets the art teacher, Nomiya, as Rin paints her mural."
    new "Hisao conhece o professor de arte, Nomiya, enquanto Rin pinta o mural dela."

    # game/definitions.rpy:224
    old "Proper Exercise"
    new "Exercício Adequado"

    # game/definitions.rpy:224
    old "Emi and Hisao discuss the importance of being in shape."
    new "Emi e Hisao discutem a importância de estar em forma."

    # game/definitions.rpy:224
    old "Sip (Part 2)"
    new "Hora do Chá (Parte 2)"

    # game/definitions.rpy:224
    old "In an attempt to kill time, Hisao goes for a walk around the school."
    new "Em uma tentativa de matar o tempo, Hisao sai para dar uma volta pela escola."

    # game/definitions.rpy:224
    old "Shanghaied"
    new "Xangptado"

    # game/definitions.rpy:224
    old "Tea, cake and competitions with Shizune and Misha at the Shanghai."
    new "Chá, bolo e competições com Shizune e Misha no Shanghai."

    # game/definitions.rpy:224
    old "Quiet"
    new "Quieto"

    # game/definitions.rpy:224
    old "Hanako and Hisao read books for the festival."
    new "Hanako e Hisao leram livros antes do festival."

    # game/definitions.rpy:224
    old "Don't Panic"
    new "Sem Pânico"

    # game/definitions.rpy:224
    old "After waking up on the day of the festival, Hisao is greeted by a ranting Kenji."
    new "Depois de acordar no dia do festival, Hisao é recebido por um Kenji furioso."

    # game/definitions.rpy:224
    old "Is Carnival!"
    new "É o Dia do Festival!"

    # game/definitions.rpy:224
    old "Emi catches Hisao eating fried food and makes him accompany her as punishment."
    new "Emi pega Hisao comendo comida frita e o faz acompanhá-la como punição."

    # game/definitions.rpy:224
    old "Clouds in My Head"
    new "Nuvens em Minha Cabeça"

    # game/definitions.rpy:224
    old "Hisao keeps Rin and her now-finished mural company."
    new "Hisao faz companhia a Rin e a seu mural agora finalizado."

    # game/definitions.rpy:224
    old "Promise of Time"
    new "Promessa de Tempo"

    # game/definitions.rpy:224
    old "After a trying morning at her stall, Hisao takes Lilly to find Hanako."
    new "Depois de uma manhã difícil em sua barraca, Hisao leva Lilly para encontrar Hanako."

    # game/definitions.rpy:224
    old "Unable to help Lilly at her stall, Hisao searches for Hanako at the festival."
    new "Incapaz de ajudar Lilly em sua barraca, Hisao procura Hanako no festival."

    # game/definitions.rpy:224
    old "Movement"
    new "Movimento"

    # game/definitions.rpy:224
    old "Lilly finishes her duties and treats Hanako and Hisao to tea at the Shanghai."
    new "Lilly termina suas tarefas e convida Hanako e Hisao para tomar chá no Xangai."

    # game/definitions.rpy:224
    old "Throwing Balls"
    new "Arremessando Bolas"

    # game/definitions.rpy:224
    old "True to his word, Hisao spends the day with Shizune and Misha."
    new "Fiel à sua palavra, Hisao passa o dia com Shizune e Misha."

    # game/definitions.rpy:224
    old "The Deep End"
    new "O Fundo do Poço"

    # game/definitions.rpy:224
    old "Kenji and Hisao share a manly picnic on the roof instead of going to the festival."
    new "Kenji e Hisao compartilham um piquenique másculo no telhado ao invés de irem para o festival."

    # game/definitions.rpy:224
    old "Emi"
    new "Emi"

    # game/definitions.rpy:224
    old "Act 2: Form"
    new "Ato 2: Forma"

    # game/definitions.rpy:224
    old "Morning Run"
    new "Corrida Matinal"

    # game/definitions.rpy:224
    old "The first of Hisao's many morning runs with Emi."
    new "A primeira de muitas corridas matinais de Hisao com Emi."

    # game/definitions.rpy:224
    old "Clouds, Time Travel, and Thou"
    new "Nuvens, Viagem no Tempo e Tu"

    # game/definitions.rpy:224
    old "Another rooftop lunch with Emi and Rin. Emi extracts from Hisao a promise to come see the track meet."
    new "Outro almoço no telhado com Emi e Rin. Emi extrai de Hisao uma promessa de ir ver a competição de atletismo."

    # game/definitions.rpy:224
    old "Questions That Need Answering!"
    new "Perguntas que Precisam de Resposta!"

    # game/definitions.rpy:224
    old "Idle chat between Emi and Hisao. Hisao asks Emi a few more questions about her relationship with Rin."
    new "Conversa fiada entre Emi e Hisao. Hisao faz mais algumas perguntas sobre seu relacionamento com a Rin."

    # game/definitions.rpy:224
    old "Second Time's the Worst"
    new "A Segunda Vez é a Pior"

    # game/definitions.rpy:224
    old "The second morning run. Hisao is almost dragged kicking and screaming around the track."
    new "A segunda corrida matinais. Hisao é quase arrastado chutando e esperneando pela pista."

    # game/definitions.rpy:224
    old "An Apple a Day"
    new "Uma Maçã por Dia"

    # game/definitions.rpy:224
    old "Hisao pays a visit to the nurse along with Emi, finding out that the two have known each other for a while."
    new "Hisao vai visitar o enfermeiro junto da Emi, descobrindo que os dois se conhecem há bastante tempo."

    # game/definitions.rpy:224
    old "Track Meeting"
    new "Competição de Atletismo"

    # game/definitions.rpy:224
    old "The day of the track meet. Another facet of Emi's personality is revealed."
    new "O dia da competição de atletismo. Outra faceta da personalidade de Emi é revelada."

    # game/definitions.rpy:224
    old "Down that Medicine Now"
    new "Tome Esses Remédios Agora"

    # game/definitions.rpy:224
    old "Hisao mentions a pain in his chest during a visit to the nurse and receives a lecture."
    new "Hisao menciona uma dor em seu peito durante uma visita ao enfermeiro e recebe um sermão."

    # game/definitions.rpy:224
    old "Piracy on the High Seas"
    new "Pirataria em Alto Mar"

    # game/definitions.rpy:224
    old "Hisao discusses his future as a pirate with Emi on the rooftop, then a letter from Iwanako spoils his day."
    new "Hisao discute seu futuro como pirata junto da Emi no telhado, depois uma carta de Iwanako estraga seu dia."

    # game/definitions.rpy:224
    old "Famous Last Words"
    new "Famosas Últimas Palavras"

    # game/definitions.rpy:224
    old "Emi and Rin take Hisao along for a picnic, soon to be spoiled by rain."
    new "Emi e Rin levam Hisao para um piquenique, que logo é arruinado pela chuva."

    # game/definitions.rpy:224
    old "Tracking Absences"
    new "Correndo Atrás Das Ausências"

    # game/definitions.rpy:224
    old "Hisao goes to the track as usual, but Emi is missing."
    new "Hisao vai à pista como de costume, mas Emi não está lá."

    # game/definitions.rpy:224
    old "Dropping By"
    new "Visitando"

    # game/definitions.rpy:224
    old "A bedside visit for a sick Emi, which quickly changes to something else entirely."
    new "Uma visita a uma Emi doente, que rapidamente muda para algo totalmente diferente."

    # game/definitions.rpy:224
    old "The First Morning After"
    new "A Primeira Manhã Após"

    # game/definitions.rpy:224
    old "Hisao reminisces about last evening, deciding to do something to help Emi."
    new "Hisao relembra a noite anterior, decidindo fazer algo para ajudar Emi."

    # game/definitions.rpy:224
    old "The (Real) Beginning"
    new "O (Verdadeiro) Começo"

    # game/definitions.rpy:224
    old "Another lunchtime on the rooftop, sans Rin."
    new "Outro almoço no telhado, sem a Rin."

    # game/definitions.rpy:224
    old "Act 3: Perspective"
    new "Ato 3: Perspectiva"

    # game/definitions.rpy:224
    old "Eet Ees… Scienca"
    new "Eet Ees... Scienca"

    # game/definitions.rpy:224
    old "Mutou pulls Hisao into a short discussion about his future."
    new "Mutou puxa Hisao para uma curta discussão sobre seu futuro."

    # game/definitions.rpy:224
    old "Definitions"
    new "Definições"

    # game/definitions.rpy:224
    old "Emi and Hisao attempt another picnic, this time without any intervention from Mother Nature."
    new "Emi e Hisao tentam fazer outro piquenique, dessa vez sem nenhuma intervenção da Mãe Natureza."

    # game/definitions.rpy:224
    old "Invisible Rock"
    new "Rocha Invisível"

    # game/definitions.rpy:224
    old "Back to the track in the morning, with business as usual… or so it seems."
    new "De volta para a pista pela manhã, com tudo conforme o normal... ou assim parecia."

    # game/definitions.rpy:224
    old "Lunch and Science"
    new "Almoço e Ciência"

    # game/definitions.rpy:224
    old "Hisao sees Mutou again about his future in the sciences."
    new "Hisao fala com Mutou novamente sobre seu futuro nas ciências."

    # game/definitions.rpy:224
    old "Up, Down, and Up Again"
    new "Para Cima, Para Baixo e Para Cima de Novo"

    # game/definitions.rpy:224
    old "A frantic call from Emi brings Hisao to her room, where two surprises await him."
    new "Uma chamada frenética de Emi traz Hisao para seu quarto, onde duas surpresas o aguardam."

    # game/definitions.rpy:224
    old "Storage Space"
    new "Espaço de Armazenamento"

    # game/definitions.rpy:224
    old "Emi coaxes Hisao into the track storage shed."
    new "Emi guia Hisao até a cabana de armazenamento da pista."

    # game/definitions.rpy:224
    old "After-School Plans"
    new "Planos Após a Escola"

    # game/definitions.rpy:224
    old "Emi has a serious talk with Hisao about the incoming exams."
    new "Emi tem uma conversa séria com Hisao sobre as provas que se aproximam."

    # game/definitions.rpy:224
    old "Detached"
    new "Desapegada"

    # game/definitions.rpy:224
    old "Hisao broods about his relationship with Emi."
    new "Hisao medita melancolicamente sobre seu relacionamento com Emi."

    # game/definitions.rpy:224
    old "Phantom Pain"
    new "Dor Fantasma"

    # game/definitions.rpy:224
    old "Hisao's attempt to show Emi his concern doesn't go nearly as well as he hoped."
    new "A tentativa de Hisao de mostrar sua preocupação com Emi não chega nem perto de ir como ele gostaria."

    # game/definitions.rpy:224
    old "Debate Expresses Doubt"
    new "Debate Expressa Dúvida"

    # game/definitions.rpy:224
    old "Hisao is confused by Emi's behavior and by an invitation to her house."
    new "Hisao está confuso pelo comportamento de Emi e por um convite para ir à casa dela."

    # game/definitions.rpy:224
    old "Guess Who's Coming… Never Mind"
    new "Adivinha Quem Vem Para... Deixa Pra Lá"

    # game/definitions.rpy:224
    old "Dinner at the Ibarazaki's."
    new "Jantar na casa dos Ibarazaki"

    # game/definitions.rpy:224
    old "Instant Replay"
    new "Repetição Instantênea"

    # game/definitions.rpy:224
    old "Things finally come to a head at the track."
    new "As coisas finalmente chegam a ápice na pista."

    # game/definitions.rpy:224
    old "Act 4: Motion"
    new "Ato 4: Movimento"

    # game/definitions.rpy:224
    old "A Swing and a Miss"
    new "Uma Tentativa e um Erro"

    # game/definitions.rpy:224
    old "Hisao wonders if Emi is purposefully avoiding him."
    new "Hisao se pergunta se Emi está o evitando de propósito."

    # game/definitions.rpy:224
    old "Saving Throw"
    new "Salvaguarda"

    # game/definitions.rpy:224
    old "Things finally come to a head on the rooftop."
    new "As coisas finalmente chegam a um ápice no telhado."

    # game/definitions.rpy:224
    old "Whispers of the Past"
    new "Sussuros do Passado"

    # game/definitions.rpy:224
    old "Hisao, Emi and her mom go for a graveside visit."
    new "Hisao, Emi e sua mãe vão para uma visita no cemitério."

    # game/definitions.rpy:224
    old "Hooray for Socks"
    new "Um Viva Para as Meias"

    # game/definitions.rpy:224
    old "Sex, drugs, but no rock and roll."
    new "Sexo, drogas, mas nenhum rock and roll."

    # game/definitions.rpy:224
    old "Clean Teeth"
    new "Dentes Limpos"

    # game/definitions.rpy:224
    old "Hisao wakes up, finding Emi sleeping next to him."
    new "Hisao desperta e encontra Emi dormindo ao seu lado."

    # game/definitions.rpy:224
    old "Hanako"
    new "Hanako"

    # game/definitions.rpy:224
    old "Act 2: Hide and Seek"
    new "Ato 2: Esconde-Esconde"

    # game/definitions.rpy:224
    old "To Town, To Town"
    new "Para a Cidade, Para a Cidade"

    # game/definitions.rpy:224
    old "A shopping trip at the convenience store with Hanako."
    new "Uma viagem até a loja de conveniências com a Hanako."

    # game/definitions.rpy:224
    old "Tea Leaves"
    new "Folhas de Chá"

    # game/definitions.rpy:224
    old "Hanako invites Hisao to have lunch with her and Lilly."
    new "Hanako convida Hisao para almoçar com ela e Lilly."

    # game/definitions.rpy:224
    old "Office Confessional"
    new "Confessionário de Escritório"

    # game/definitions.rpy:224
    old "Hisao and Misha discuss the plight of Hanako."
    new "Hisao e Misha discutem a situação da Hanako."

    # game/definitions.rpy:224
    old "Chess and Slides"
    new "Xadrez e Escorregadores"

    # game/definitions.rpy:224
    old "Hisao ditches the Student Council to read with Hanako."
    new "Hisao dispensa o Conselho Estudantil para ler com a Hanako."

    # game/definitions.rpy:224
    old "Rise and Shine"
    new "Levante-se e Brilhe"

    # game/definitions.rpy:224
    old "An invitation from Lilly to a tea party after hours."
    new "Um convite da Lilly para uma festa de chá em altas horas."

    # game/definitions.rpy:224
    old "Mad Hatter"
    new "Chapeleiro Maluco"

    # game/definitions.rpy:224
    old "Hanako, Hisao and Lilly meet together to have tea in Lilly's room."
    new "Hanako, Hisao e Lilly se unem para tomar chá no quarto da Lilly."

    # game/definitions.rpy:224
    old "Small Change"
    new "Uma Nota de Mudança"

    # game/definitions.rpy:224
    old "Kenji is forced to repay his loan."
    new "Kenji é forçado a pagar seu empréstimo."

    # game/definitions.rpy:224
    old "Absenteeism"
    new "Ausência"

    # game/definitions.rpy:224
    old "Hisao and Lilly discuss Hanako's school attendance."
    new "Hisao e Lilly discutem a presença de Hanako nas aulas."

    # game/definitions.rpy:224
    old "Equivalent Exchange"
    new "Troca Equivalente"

    # game/definitions.rpy:224
    old "In return for learning about his heart, Hanako reveals part of her past to Hisao."
    new "Em troca de aprender sobre o coração de Hisao, Hanako revela parte de seu passado para ele."

    # game/definitions.rpy:224
    old "Act 3: Castling"
    new "Ato 3: Roque"

    # game/definitions.rpy:224
    old "Invitation"
    new "Convite"

    # game/definitions.rpy:224
    old "Lilly finds Hisao cleaning up the Tea Room and tells him about Hanako's birthday."
    new "Lilly encontra Hisao limpando a Sala de Chá e avisa ele sobre o aniversário de Hanako."

    # game/definitions.rpy:224
    old "Shady Encounter"
    new "Encontro Obscuro"

    # game/definitions.rpy:224
    old "An unexpected chat with Miki while reminiscing about the past."
    new "Uma conversa inesperada com Miki enquanto remói o passado."

    # game/definitions.rpy:224
    old "Antiques and Pie"
    new "Antiguidades e Torta"

    # game/definitions.rpy:224
    old "Lilly and Hisao shop for a present in the city."
    new "Lilly e Hisao vão comprar um presente na cidade."

    # game/definitions.rpy:224
    old "Falling"
    new "Caindo"

    # game/definitions.rpy:224
    old "Hanako has a panic attack during class."
    new "Hanako tem um ataque de pânico durante a aula."

    # game/definitions.rpy:224
    old "Treading Softly"
    new "Andando Com Cuidado"

    # game/definitions.rpy:224
    old "Lilly has bad news to discuss with Hisao and Hanako."
    new "Lilly tem más notícias para discutir com Hisao e Hanako."

    # game/definitions.rpy:224
    old "Reaching Out"
    new "Alcançando"

    # game/definitions.rpy:224
    old "Hisao reaches out to a withdrawn Hanako."
    new "Hisao Vai Atrás de Uma Hanako Retraída."

    # game/definitions.rpy:224
    old "One More Year"
    new "Mais um Ano"

    # game/definitions.rpy:224
    old "Our trio is joined by an unexpected guest as they celebrate Hanako's birthday party."
    new "Nosso trio ganha a presença de um convidado inesperado enquanto comemoram o aniversário da Hanako."

    # game/definitions.rpy:224
    old "One Piece of Paper"
    new "Um Pedaço de Papel"

    # game/definitions.rpy:224
    old "Hisao enjoys his first hangover, before receiving a troubling letter."
    new "Hisao desfruta sua primeira ressaca, antes de receber uma carta problemática."

    # game/definitions.rpy:224
    old "Stripes and Solids"
    new "Sólidas e Listradas"

    # game/definitions.rpy:224
    old "Heart-to-heart during a game of pool."
    new "Um conversa de coração durante um jogo de sinuca."

    # game/definitions.rpy:224
    old "Beginning of the End"
    new "Começo do Fim"

    # game/definitions.rpy:224
    old "Lilly's departure for her trip."
    new "Lilly Parte Para Sua Viagem."

    # game/definitions.rpy:224
    old "Act 4: Scars"
    new "Ato 4: Cicatrizes"

    # game/definitions.rpy:224
    old "Truancy"
    new "Ausência Escolar"

    # game/definitions.rpy:224
    old "Lunch with the Student Council and worry about Hanako shutting herself in."
    new "Almoço com o Conselho Estudantil e preocupação com a Hanako se isolando."

    # game/definitions.rpy:224
    old "Faraway Presence"
    new "Presença Remota"

    # game/definitions.rpy:224
    old "Hisao phones Lilly for advice after Hanako secludes herself for another day."
    new "Hisao liga para Lilly para pedir conselhos após Hanako se isolar por outro dia."

    # game/definitions.rpy:224
    old "Misstep"
    new "Passo em Falso"

    # game/definitions.rpy:224
    old "Hisao tries to pull Hanako out of her room, with startling results."
    new "Hisao tenta tirar Hanako do quarto dela, tendo resultados inesperados."

    # game/definitions.rpy:224
    old "Cut Petals"
    new "Cortar Pétalas"

    # game/definitions.rpy:224
    old "Hisao finds his future relationship with Hanako prematurely ended."
    new "Hisao encontra sua futura relação com Hanako terminada prematuramente."

    # game/definitions.rpy:224
    old "Continuing Melody"
    new "A Melodia Contínua"

    # game/definitions.rpy:224
    old "Hanako returns to class, to Hisao's relief."
    new "Hanako volta para a aula, para alívio de Hisao."

    # game/definitions.rpy:224
    old "Shanghai Studiousness"
    new "Estudiosidade no Xangai"

    # game/definitions.rpy:224
    old "Attempting to avoid distractions, Hisao tries studying at the Shanghai."
    new "Buscando evitar distrações, Hisao tenta estudar no Xangai."

    # game/definitions.rpy:224
    old "His Past"
    new "O Passado Dele"

    # game/definitions.rpy:224
    old "In an attempt to come closer to Hanako, Hisao shares a part of his past with her."
    new "Na intenção de se aproximar da Hanako, Hisao compartilha parte de seu passado com ela."

    # game/definitions.rpy:224
    old "City Rendezvous"
    new "Encontro na Cidade"

    # game/definitions.rpy:224
    old "The two share a date in the city."
    new "Os dois compartilham um encontro na cidade."

    # game/definitions.rpy:224
    old "Whispered Touch"
    new "Toque Sussurrado"

    # game/definitions.rpy:224
    old "Hisao and Hanako spend the night together."
    new "Hisao e Hanako passam a noite juntos."

    # game/definitions.rpy:224
    old "Indeterminate Future"
    new "Futuro Indeterminado"

    # game/definitions.rpy:224
    old "The events of the previous night weigh heavily on Hisao."
    new "Os eventos da noite anterior pesam bastante sobre Hisao."

    # game/definitions.rpy:224
    old "Adulthood"
    new "Maioridade"

    # game/definitions.rpy:224
    old "The end of two children, the beginning of two adults."
    new "O fim de duas crianças, o começo de dois adultos."

    # game/definitions.rpy:224
    old "Lilly"
    new "Lilly"

    # game/definitions.rpy:224
    old "Act 2: Past"
    new "Ato 2: Passado"

    # game/definitions.rpy:224
    old "Earl Grey"
    new "Earl Grey"

    # game/definitions.rpy:224
    old "Hisao shares the first of many lunchbreaks with Hanako and Lilly, recovering from the day before."
    new "Hisao compartilha o primeiro de muitos almoços com Hanako e Lilly, se recuperando do dia anterior."

    # game/definitions.rpy:224
    old "A Pound Sterling"
    new "Uma Libra Esterlina"

    # game/definitions.rpy:224
    old "Questioned by Kenji on Lilly's nationality, Hisao decides to investigate and finds out a great deal more."
    new "Questionado por Kenji sobre a nacionalidade de Lilly, Hisao decide investigar e descobre muito mais."

    # game/definitions.rpy:224
    old "Presents and Presence"
    new "Presentes e Presença"

    # game/definitions.rpy:224
    old "While out in search of a present for Hanako, Lilly and Hisao meet Akira and her cousin."
    new "Durante a procura por um presente para Hanako, Lilly e Hisao encontram Akira e seu primo."

    # game/definitions.rpy:224
    old "Unidentified Drinking Object"
    new "Objeto para Beber Não Identificado"

    # game/definitions.rpy:224
    old "The trio hold a birthday party for Hanako, interrupted by the surprise appearance of a sibling."
    new "O trio faz uma festa de aniversário para Hanako, interrompida pela aparição surpresa de uma irmã."

    # game/definitions.rpy:224
    old "The Day After"
    new "O Dia Seguinte"

    # game/definitions.rpy:224
    old "Hisao and Lilly awaken and try to recuperate from the previous evening's events."
    new "Hisao e Lilly acordam e tentam se recuperar dos eventos da noite anterior."

    # game/definitions.rpy:224
    old "A Brief History of Thyme"
    new "Uma Breve História do Tempero"

    # game/definitions.rpy:224
    old "Hisao and Lilly go to get some groceries."
    new "Hisao e Lilly vão comprar algumas coisas na loja."

    # game/definitions.rpy:224
    old "Little Wing"
    new "Little Wing"

    # game/definitions.rpy:224
    old "A shared lunch on the roof takes an unfortunate turn."
    new "Um almoço compartilhado no telhado toma um rumo ruim."

    # game/definitions.rpy:224
    old "Bon Voyage"
    new "Bon Voyage"

    # game/definitions.rpy:224
    old "Lilly and Akira get seen off as they leave for a trip to their family in Scotland."
    new "Lilly e Akira ganham uma despedida antes de partirem para a viagem para ver sua família na Escócia."

    # game/definitions.rpy:224
    old "Act 3: Present"
    new "Ato 3: Presente"

    # game/definitions.rpy:224
    old "Day by Day"
    new "Dia a Dia"

    # game/definitions.rpy:224
    old "Hisao idly lets a day without Lilly slip by, having a talk with Mutou about Yamaku."
    new "Hisao deixa passar um dia sem a Lilly, conversando com Mutou sobre a Yamaku."

    # game/definitions.rpy:224
    old "Minor Discord"
    new "Pequena Discórdia"

    # game/definitions.rpy:224
    old "Hisao has lunch with Kenji, then gives some handouts to an alarmingly silent Hanako."
    new "Hisao almoça com Kenji, e depois passa algumas tarefas para uma Hanako notoriamente quieta."

    # game/definitions.rpy:224
    old "Dissonance"
    new "Dissonância"

    # game/definitions.rpy:224
    old "With Hanako withdrawing into herself completely, Hisao offers what little help he can before calling Lilly."
    new "Com Hanako se isolando completamente, Hisao oferece a pouca ajuda que consegue antes de ligar para Lilly."

    # game/definitions.rpy:224
    old "A World Away"
    new "Um Mundo de Distância"

    # game/definitions.rpy:224
    old "Hisao's reassured mind begins to wonder about the relationship between he and Lilly."
    new "A mente tranquila de Hisao começa a se perguntar sobre o relacionamento entre ele e Lilly."

    # game/definitions.rpy:224
    old "Renewal"
    new "Renovação"

    # game/definitions.rpy:224
    old "Hisao, Hanako, and Hideaki welcome Akira and Lilly after their return from Scotland."
    new "Hisao, Hanako, e Hideaki dão boas-vindas para Akira e Lilly depois do retorno delas da Escócia."

    # game/definitions.rpy:224
    old "Northern Sojourn"
    new "Estadia no Norte"

    # game/definitions.rpy:224
    old "The trio begins their holiday in Hokkaido."
    new "O trio começa seu feriado em Hokkaido."

    # game/definitions.rpy:224
    old "Prelude"
    new "Prelúdio"

    # game/definitions.rpy:224
    old "A morning walk begins a chain of events."
    new "Uma caminhada matinal começa uma cadeia de eventos."

    # game/definitions.rpy:224
    old "Crescendo"
    new "Crescendo"

    # game/definitions.rpy:224
    old "Lilly's true feelings are told in the endless gold of the wheat fields."
    new "Os verdadeiros sentimentos de Lilly são contados no dourado sem fim dos campos de trigo."

    # game/definitions.rpy:224
    old "Diminuendo"
    new "Diminuendo"

    # game/definitions.rpy:224
    old "Our couple shares their first night together."
    new "Nosso casal compartilha a sua primeira noite juntos."

    # game/definitions.rpy:224
    old "Gray Outlook"
    new "Perspectiva Cinzenta"

    # game/definitions.rpy:224
    old "Confined to the summerhouse, Lilly and Hisao are forced to come to terms with their relationship."
    new "Confinados na casa de verão, Lilly e Hisao são forçados a encarar o relacionamento deles."

    # game/definitions.rpy:224
    old "Rhapsody in Blue"
    new "Rapsódia em Azul"

    # game/definitions.rpy:224
    old "A bathing Hisao reflects on where he and Lilly are in life, before being joined by someone."
    new "Um banho onde Hisao reflete sobre onde ele e Lilly estão na vida, antes de alguém se juntar a ele."

    # game/definitions.rpy:224
    old "The Momentary Present"
    new "O Presente Momentâneo"

    # game/definitions.rpy:224
    old "Traveling back to Yamaku, Hisao and Lilly idly talk between themselves."
    new "Viajando de volta para Yamaku, Hisao e Lilly conversam distraídamente entre si."

    # game/definitions.rpy:224
    old "Act 4: Future"
    new "Ato 4: Futuro"

    # game/definitions.rpy:224
    old "Slow Steps 'Fore a Waltz"
    new "Passos Lentos Antes de uma Valsa"

    # game/definitions.rpy:224
    old "Back at the school, the events of Hokkaido come to the fore."
    new "De volta na escola, os eventos de Hokkaido vem à tona."

    # game/definitions.rpy:224
    old "Pajamas and Suits"
    new "Pijamas e Ternos"

    # game/definitions.rpy:224
    old "Settling back into daily life. Akira joins the trio during one of their tea parties."
    new "Voltando para a vida escolar. Akira se junta ao trio durante uma de suas festas do chá."

    # game/definitions.rpy:224
    old "Correct Procedure"
    new "Procedimento Correto"

    # game/definitions.rpy:224
    old "Hisao and Lilly arrange a date, before Akira swings by."
    new "Hisao e Lilly marcam um encontro, antes de Akira passar por lá."

    # game/definitions.rpy:224
    old "Out and About"
    new "Um Dia Fora"

    # game/definitions.rpy:224
    old "Hisao and Lilly go on their first date, finding out about each other's pasts."
    new "Hisao e Lilly vão em seu primeiro encontro, descobrindo os passados um do outro."

    # game/definitions.rpy:224
    old "A Morning's Reverie"
    new "Um Devaneio Matinal"

    # game/definitions.rpy:224
    old "Hisao and Lilly discuss their ambitions for the future."
    new "Hisao e Lilly discutem suas ambições para o futuro."

    # game/definitions.rpy:224
    old "Blackout"
    new "Apagão"

    # game/definitions.rpy:224
    old "The trio muse on the upcoming holidays, before Hisao experiences sight as Lilly does."
    new "O trio reflete sobre as férias que estão chegando, antes de Hisao experienciar a visão da mesma maneira que Lilly."

    # game/definitions.rpy:224
    old "Context"
    new "Contexto"

    # game/definitions.rpy:224
    old "Hisao gets called out by Akira and the two talk about her sibling."
    new "Hisao recebe uma chamada da Akira e os dois conversam sobre a irmã dela."

    # game/definitions.rpy:224
    old "A Faraway Future"
    new "Um Futuro Distante"

    # game/definitions.rpy:224
    old "Lilly reveals her family's offer to join them in Scotland."
    new "Lilly revela para Hisao a oferta da família dela para ela se juntar a eles na Escócia."

    # game/definitions.rpy:224
    old "Farewell"
    new "Despedida"

    # game/definitions.rpy:224
    old "Farewells to Akira and Lilly the evening before they leave Japan."
    new  "Despedidas para Akira e Lilly na noite antes delas deixarem o Japão."

    # game/definitions.rpy:224
    old "False Cadence"
    new "Falsa Cadência"

    # game/definitions.rpy:224
    old "Hisao rushes to confront Lilly, realizing her conflict."
    new "Hisao se apressa para confrontar Lilly, percebendo o conflito dela."

    # game/definitions.rpy:224
    old "Under a Maudlin Sky"
    new "Sob um Céu Garoante"

    # game/definitions.rpy:224
    old "Waking in the hospital ward, Hisao struggles to come to terms with his life."
    new "Acordando na ala do hospital, Hisao sente dificuldades em aceitar sua vida nova."

    # game/definitions.rpy:224
    old "Under a Bright Sky"
    new "Sob um Céu Brilhante"

    # game/definitions.rpy:224
    old "Lilly rejoins Hisao, the two beginning their life together anew."
    new "Lilly se reúne com Hisao, os dois começando sua vida juntos novamente."

    # game/definitions.rpy:224
    old "Forwards, with Gusto!"
    new "Adiante, com Gosto!"

    # game/definitions.rpy:224
    old "Lilly and Hisao see off Akira."
    new "Lilly e Hisao se despedem de Akira."

    # game/definitions.rpy:224
    old "Rin"
    new "Rin"

    # game/definitions.rpy:224
    old "Act 2: Disconnect"
    new "Ato 2: Desconexão"

    # game/definitions.rpy:224
    old "A Wider Field of Vision"
    new "Um Campo de Visão Mais Amplo"

    # game/definitions.rpy:224
    old "Hisao spends a lunch break with Rin watching clouds on the rooftop."
    new "Hisao passa o intervalo do almoço olhando as nuvens no telhado com Rin."

    # game/definitions.rpy:224
    old "Studies in Grayscale"
    new "Estudos em Escala de Cinzas"

    # game/definitions.rpy:224
    old "Rin and Hisao draw portraits of each other at his first art club meeting."
    new "Rin e Hisao desenham retratos um do outro no primeiro encontro dele no clube de artes."

    # game/definitions.rpy:224
    old "Interstitial"
    new "Intersticial"

    # game/definitions.rpy:224
    old "Kenji lends a “borrowed” book to Hisao."
    new "Kenji empresta um livro “emprestado” para Hisao."

    # game/definitions.rpy:224
    old "Self Study"
    new "Auto-estudo"

    # game/definitions.rpy:224
    old "Misha and Shizune catch Hisao meditatively doodling during class."
    new "Misha e Shizune pegam Hisao desenhando pensativamente durante a aula."

    # game/definitions.rpy:224
    old "Hisao's Smile"
    new "O Sorriso de Hisao"

    # game/definitions.rpy:224
    old "Rin talks to Hisao about his happy expressions, or lack of them."
    new "Rin fala com Hisao sobre as expressões de alegria dele, ou a falta delas."

    # game/definitions.rpy:224
    old "Things You Like"
    new "Coisas Que Você Gosta"

    # game/definitions.rpy:224
    old "Brief musings with Yuuko about books and Yamaku."
    new "Breves reflexões com Yuuko sobre livros e Yamaku."

    # game/definitions.rpy:224
    old "Target Audience"
    new "Público Alvo"

    # game/definitions.rpy:224
    old "The day of the track meet. Facets of Emi's and Rin's personalities get revealed."
    new "O dia da competição de atletismo. Facetas das personalidades de Emi e Rin são reveladas."

    # game/definitions.rpy:224
    old "Eternity In an Hour"
    new "Eternidade em Uma Hora"

    # game/definitions.rpy:224
    old "Nomiya incites discussion of art during a club meeting."
    new "Nomiya incita uma discussão sobre arte durante uma reunião do clube."

    # game/definitions.rpy:224
    old "Underwater and a Maple with a Name"
    new "Debaixo D'Água e um Bordo com Nome"

    # game/definitions.rpy:224
    old "Rin leads Hisao into the woods, where they ponder their immediate future."
    new "Rin leva Hisao para a floresta, onde eles ponderam sobre seu futuro imediato."

    # game/definitions.rpy:224
    old "Iwanako's Regret"
    new "O Arrependimento de Iwanako"

    # game/definitions.rpy:224
    old "A letter from Iwanako arrives."
    new "Chega uma carta de Iwanako."

    # game/definitions.rpy:224
    old "In Her Own Image"
    new "Em Sua Própria Imagem"

    # game/definitions.rpy:224
    old "Hisao pushes Rin to have her own art exhibition."
    new "Hisao impulsiona Rin para ela ter sua própria exibição de arte."

    # game/definitions.rpy:224
    old "Umbrella Logic Cake"
    new "Bolo de Lógica do Guarda-Chuva"

    # game/definitions.rpy:224
    old "Emi, Hisao and Rin get rained on and seek refuge in the Shanghai."
    new "Emi, Hisao e Rin tomam chuva e procuram refúgio no Xangai."

    # game/definitions.rpy:224
    old "Six Meters Closer to Heaven"
    new "Seis Metros Mais Perto do Céu"

    # game/definitions.rpy:224
    old "Rin and Hisao DON'T eat lunch on the roof, due to a distinct lack of Emi."
    new "Rin e Hisao NÃO almoçam no telhado, devido a uma distinta falta da Emi."

    # game/definitions.rpy:224
    old "Indecision"
    new "Indecisão"

    # game/definitions.rpy:224
    old "Emi gets rid of her cold, while Rin catches her own."
    new "Emi se cura de seu resfriado, enquanto Rin pega um resfriado próprio."

    # game/definitions.rpy:224
    old "Signal Interference"
    new "Interferência de Sinal"

    # game/definitions.rpy:224
    old "Hisao goes visit Rin in her room."
    new "Hisao vai visitar Rin em seu quarto."

    # game/definitions.rpy:224
    old "Dandelions"
    new "Dentes de Leão"

    # game/definitions.rpy:224
    old "Conclusions get drawn on a hilltop."
    new "Conclusões são feitas no topo de um morro."

    # game/definitions.rpy:224
    old "Act 3: Distance"
    new "Ato 3: Distância"

    # game/definitions.rpy:224
    old "22nd Corner"
    new "Vigésima Segunda Esquina"

    # game/definitions.rpy:224
    old "The art club team checks out the gallery for Rin's future exhibition."
    new "A equipe do clube de artes visita a galeria da futura exibição de Rin."

    # game/definitions.rpy:224
    old "The Scent of Light"
    new "O Aroma da Luz"

    # game/definitions.rpy:224
    old "Hisao happens upon a sleeping Rin in the art room."
    new "Hisao topa com uma Rin dormindo na sala de arte."

    # game/definitions.rpy:224
    old "Things You Can't Give Up"
    new "Coisas que Você Não Pode Desistir"

    # game/definitions.rpy:224
    old "Emi and Hisao discuss Rin's personality."
    new "Emi e Hisao discutem a personalidade de Rin."

    # game/definitions.rpy:224
    old "BADAAN!"
    new "TUM!"

    # game/definitions.rpy:224
    old "Yuuko's thoughts on motivation."
    new "Os pensamentos de Yuuko sobre motivação."

    # game/definitions.rpy:224
    old "Rose-Tinted Glasses"
    new "Óculos Cor-de-Rosa"

    # game/definitions.rpy:224
    old "Nomiya expounds at length about art as a career."
    new "Nomiya discursa longamente sobre a arte como uma carreira."

    # game/definitions.rpy:224
    old "The Edge of the World"
    new "A Beirada do Mundo"

    # game/definitions.rpy:224
    old "Hisao confesses to Rin and gets shot down. Or does he?"
    new "Hisao confessa seu amor para Rin e é rejeitado. Ou não?"

    # game/definitions.rpy:224
    old "The Context of Rin"
    new "O Contexto de Rin"

    # game/definitions.rpy:224
    old "An awkward and silent afternoon at the atelier."
    new "Uma incômoda e silenciosa tarde no ateliê."

    # game/definitions.rpy:224
    old "Fast Forward"
    new "Passando Para Frente"

    # game/definitions.rpy:224
    old "The preparations for the exhibition settle into a strange routine."
    new "As preparações para a exibição entram em uma rotina estranha."

    # game/definitions.rpy:224
    old "Self-Destruction"
    new "Autodestruição"

    # game/definitions.rpy:224
    old "Rin experiments with smoking to get a fresh look at creativity."
    new "Rin experimenta fumar para conseguir um olhar novo na criatividade."

    # game/definitions.rpy:224
    old "Reverse Escapism"
    new "Escapismo Reverso"

    # game/definitions.rpy:224
    old "Hisao takes Rin on a walk through the night streets."
    new "Hisao leva Rin para andar pelas ruas noturnas."

    # game/definitions.rpy:224
    old "Boundless"
    new "Sem Limites"

    # game/definitions.rpy:224
    old "Sae and Nomiya give Hisao some insight on artists' lives."
    new "Sae e Nomiya dão um pouco de entendimento para Hisao sobre a vida de artistas."

    # game/definitions.rpy:224
    old "Delirium"
    new "Delírio"

    # game/definitions.rpy:224
    old "Hisao surprises a desperate Rin in the atelier."
    new "Hisao surpreende uma Rin desesperada no ateliê."

    # game/definitions.rpy:224
    old "Things You Hate"
    new "Coisas Que Você Odeia"

    # game/definitions.rpy:224
    old "Unpleasant aftermath of an incredible night."
    new "Desagradáveis consequências de uma noite incrível."

    # game/definitions.rpy:224
    old "Shards of Ire"
    new "Fragmentos de Ira"

    # game/definitions.rpy:224
    old "The strained relationship between the two blows apart."
    new "O tenso relacionamento entre os dois explode."

    # game/definitions.rpy:224
    old "Act 4: Dream"
    new "Ato 4: Sonho"

    # game/definitions.rpy:224
    old "Illusions for People"
    new "Ilusões para Pessoas"

    # game/definitions.rpy:224
    old "Hisao talks about his misgivings to Nomiya, to little effect."
    new "Hisao fala sobre seus receios com Nomiya, sem sucesso."

    # game/definitions.rpy:224
    old "Demused"
    new "Desinspirado"

    # game/definitions.rpy:224
    old "Hisao's patience comes to an end."
    new "A paciência de Hisao chega a um fim."

    # game/definitions.rpy:224
    old "The Scene"
    new "A Cena"

    # game/definitions.rpy:224
    old "Meeting with Rin at the exhibition opening."
    new "Encontro com Rin na abertura da exibição."

    # game/definitions.rpy:224
    old "Wavelength"
    new "Sintonia"

    # game/definitions.rpy:224
    old "Hisao lethargically whiles away the last day of exams."
    new "Hisao deixa o último dia das provas passar letargicamente."

    # game/definitions.rpy:224
    old "Blue Period"
    new "Período Azul"

    # game/definitions.rpy:224
    old "A rainy day, the 22nd Corner, and a brief history of Picasso."
    new "Um dia chuvoso, a Vigésima Segunda Esquina, e uma breve história sobre Picasso."

    # game/definitions.rpy:224
    old "The World Only You Can See"
    new "O Mundo Que Apenas Você Consegue Ver"

    # game/definitions.rpy:224
    old "Rin and Hisao part after the rain."
    new "Rin e Hisao se separam após a chuva."

    # game/definitions.rpy:224
    old "Desperate Glory"
    new "Glória Desesperada"

    # game/definitions.rpy:224
    old "A frantic Nomiya queries Hisao about Rin's whereabouts."
    new "Um Nomiya agitado questiona Hisao sobre o paradeiro de Rin."

    # game/definitions.rpy:224
    old "Problems of Self-Referential Logic"
    new "Problemas de Lógica Autorreferencial"

    # game/definitions.rpy:224
    old "Hisao finds Rin in her hiding place, and convinces her to reconcile with Nomiya."
    new "Hisao encontra Rin em seu esconderijo, e convence ela a se reconciliar com Nomiya."

    # game/definitions.rpy:224
    old "Measuring Shadows"
    new "Medindo Sombras"

    # game/definitions.rpy:224
    old "Rin's apology to the art teacher isn't well-received."
    new "A desculpa de Rin para o professor de artes não é bem recebida."

    # game/definitions.rpy:224
    old "Raison d'être"
    new "Raison d'être"

    # game/definitions.rpy:224
    old "Hisao comforts an upset Rin."
    new "Hisao conforta uma Rin chateada."

    # game/definitions.rpy:224
    old "Without Breathing, Without a Sound"
    new "Sem Respirar, Sem um Som"

    # game/definitions.rpy:224
    old "On the first day of summer vacation, Rin comes to Hisao's room."
    new "No primeiro dia das férias de verão, Rin vem ao quarto de Hisao."

    # game/definitions.rpy:224
    old "Proof of Existence"
    new "Prova de Existência"

    # game/definitions.rpy:224
    old "Everything comes together on that dandelion-covered hilltop."
    new "Tudo se une e fica bem naquele topo de morro coberto por dentes de leão."

    # game/definitions.rpy:224
    old "Shizune"
    new "Shizune"

    # game/definitions.rpy:224
    old "Act 2: Learning to Read"
    new "Ato 2: Aprendendo a Ler"

    # game/definitions.rpy:224
    old "Message Passing"
    new "Passando Mensagens"

    # game/definitions.rpy:224
    old "Shizune and Hisao explore methods of communication."
    new "Shizune e Hisao exploram métodos de comunicação."

    # game/definitions.rpy:224
    old "Talk to the Hand"
    new "Fale Com a Minha Mão"

    # game/definitions.rpy:224
    old "Hisao begins studying a new language, and a tutor appears."
    new "Hisao começa a estudar um novo idioma, e uma tutora aparece."

    # game/definitions.rpy:224
    old "Chinese Whispers"
    new "Telefone sem Fio"

    # game/definitions.rpy:224
    old "Kenji manages to coerce Hisao to do a favor for him, but Hisao runs into trouble in many forms."
    new "Kenji consegue coagir Hisao a fazer um favor para ele, mas Hisao encontra problemas de várias formas."

    # game/definitions.rpy:224
    old "Advanced Game Theory"
    new "Teoria dos Jogos Avançada"

    # game/definitions.rpy:224
    old "RISK isn't enough any more to satiate Shizune's hunger. What's worse, a new opponent makes her appearance."
    new "Risk não é mais o bastante para satisfazer a fome de Shizune. O que é pior, uma nova oponente faz sua aparição."

    # game/definitions.rpy:224
    old "Bread, Scissors, Paper"
    new "Pão, Tesoura, Papel"

    # game/definitions.rpy:224
    old "A lazy afternoon becomes dramatic as suddenly a piece of bread becomes an object of extreme interest."
    new "Uma tarde tranquila se torna dramática assim que um pedaço de pão de torna um objeto de extremo interesse."

    # game/definitions.rpy:224
    old "Interface"
    new "Interface"

    # game/definitions.rpy:224
    old "Shizune and Hisao find a connection."
    new "Shizune e Hisao acham uma conexão."

    # game/definitions.rpy:224
    old "Spring into Action"
    new "Entrar em Ação"

    # game/definitions.rpy:224
    old "Hisao has to mediate between Lilly and Shizune, but luckily things work out in the end."
    new "Hisao tem que mediar entre Lilly e Shizune, mas por sorte as coisas se arrumam no final."

    # game/definitions.rpy:224
    old "Past Imperfective"
    new "Passado Imperfectivo"

    # game/definitions.rpy:224
    old "The Student Council reminisces about past years while relaxing at the Shanghai."
    new "O Conselho Estudantil se lembra dos anos passados enquanto relaxando no Shanghai."

    # game/definitions.rpy:224
    old "When Stars Embrace"
    new "Quando Estrelas Abraçam"

    # game/definitions.rpy:224
    old "It's finally time for Tanabata!"
    new "Finalmente é hora do Tanabata!"

    # game/definitions.rpy:224
    old "Act 3: Sleight of Hand"
    new "Ato 3: Truque de Mãos"

    # game/definitions.rpy:224
    old "Force Feedback"
    new "Feedback à Força"

    # game/definitions.rpy:224
    old "Hisao finds out that Shizune is going to visit her family, and manages to come along."
    new "Hisao descubre que Shizune vai visitar a família dela, e consegue ir junto."

    # game/definitions.rpy:224
    old "United Nations"
    new "Nações Unidas"

    # game/definitions.rpy:224
    old "The trip to Shizune's house, meeting her little brother, and a sudden fishing contest."
    new "A viagem para a casa de Shizune, conhecer o irmão menor dela, e uma súbita competição de pesca."

    # game/definitions.rpy:224
    old "Use-Mention Distinction"
    new "Distinção de Uso-Menção"

    # game/definitions.rpy:224
    old "Hideaki tries to entertain Hisao for a day, meeting with little success."
    new "Hideaki tenta entreter Hisao por um dia, encontrando pouco sucesso."

    # game/definitions.rpy:224
    old "Family Plot"
    new "Casos Familiares"

    # game/definitions.rpy:224
    old "Our trio meets Shizune's father and immediately beats a hasty retreat."
    new "Nosso trio encontra o pai de Shizune e imediatamente faz uma rápida retirada."

    # game/definitions.rpy:224
    old "Pangrammatic Window"
    new "Janela Pangramática"

    # game/definitions.rpy:224
    old "A request from Hideaki to learn sign language unexpectedly escalates into a shouting match with Jigoro."
    new "Um pedido de Hideaki para aprender Linguagem de Sinais inesperadamente se torna uma gritaria com Jigoro."

    # game/definitions.rpy:224
    old "Closer"
    new "Mais Pertos"

    # game/definitions.rpy:224
    old "Shizune and Hisao join together for the first time."
    new "Shizune e Hisao se juntam pela primeira vez."

    # game/definitions.rpy:224
    old "Confrontation"
    new "Confrontação"

    # game/definitions.rpy:224
    old "Jigoro belittles the Student Council and Hisao rises up to the challenge."
    new "Jigoro menospreza o Conselho Estudantil e Hisao se ergue para o desafio."

    # game/definitions.rpy:224
    old "The Anchor"
    new "A Âncora"

    # game/definitions.rpy:224
    old "Back to Yamaku. A letter from Iwanako prompts a lengthy discussion from Kenji on the finer points of girlfriends."
    new "De volta em Yamaku. Uma carta de Iwanako faz surgir uma longa discussão de Kenji sobre pontos mais importantes de namoradas."

    # game/definitions.rpy:224
    old "Roadmap"
    new "Mapa do Caminho"

    # game/definitions.rpy:224
    old "The Student Council worries about their replacement, and Hisao ends up treating Misha to a parfait somehow."
    new "O Conselho Estudantil se preocupa com seus substitutos, e Hisao acaba, de alguma forma, comprando um parfait para Misha."

    # game/definitions.rpy:224
    old "Acute Triangle"
    new "Triângulo Afiado"

    # game/definitions.rpy:224
    old "An afternoon of work with Shizune shows Hisao that something is amiss between the girls."
    new "Uma tarde de trabalho com Shizune mostra a Hisao que tem algo de errado entre as garotas."

    # game/definitions.rpy:224
    old "Dewey Decimated"
    new "Dewey Decimado"

    # game/definitions.rpy:224
    old "Yuuko gets Hisao to watch the library for her. The arrival of Kenji makes the attempt meet with mixed success."
    new "Yuuko consegue que Hisao olhe a biblioteca por ela. A chegada de Kenji questiona o sucesso da tentativa."

    # game/definitions.rpy:224
    old "Tongue-Tied"
    new "Língua Presa"

    # game/definitions.rpy:224
    old "Misha visits Hisao in his room, and things go in an unexpected direction."
    new "Misha visita Hisao no quarto dele e as coisas tomam um rumo inesperado."

    # game/definitions.rpy:224
    old "Look Aside"
    new "Olhe Para o Lado"

    # game/definitions.rpy:224
    old "Hisao meets a depressed Misha on the roof. He ends up pushing her and Shizune together."
    new "Hisao encontra uma Misha deprimida no telhado. Ele acaba empurrando ela e Shizune juntas."

    # game/definitions.rpy:224
    old "Look Ahead"
    new "Olhe Para Frente"

    # game/definitions.rpy:224
    old "Hisao meets a depressed Misha on the roof. Shizune joins them and pulls the whole council back to work."
    new "Hisao encontra uma Misha deprimida no telhado. Shizune se junta a eles e põe o Conselho todo de volta ao trabalho."

    # game/definitions.rpy:224
    old "Act 4: To My Other Self"
    new "Ato 4: Para o Meu Outro Eu"

    # game/definitions.rpy:224
    old "Grand Strategy"
    new "Grande Estratégia"

    # game/definitions.rpy:224
    old "Shizune confesses to Hisao some of her goals and failures."
    new "Shizune confessa para Hisao alguns de seus objetivos e fracassos."

    # game/definitions.rpy:224
    old "Off by One"
    new "Por um Triz"

    # game/definitions.rpy:224
    old "A failed attempt to cheer up Misha gets converted into an impromptu date for Hisao and Shizune."
    new "Uma tentativa falha de animar Misha se converte em um encontro improvisado para Hisao e Shizune."

    # game/definitions.rpy:224
    old "Invasion"
    new "Invasão"

    # game/definitions.rpy:224
    old "Jigoro and Hideaki pay Shizune an unexpected and somewhat unpleasant visit."
    new "Jigoro e Hideaki fazem uma visita inesperada e meio desagradável para Shizune."

    # game/definitions.rpy:224
    old "Parfait"
    new "Parfait"

    # game/definitions.rpy:224
    old "Hisao and Shizune stalk Misha. Hisao finally manages to corner her and discuss things properly."
    new "Hisao e Shizune seguem Misha. Hisao finalmente consegue encurralá-la e discutem as coisas apropriadamente."

    # game/definitions.rpy:224
    old "The Summit"
    new "O Topo"

    # game/definitions.rpy:224
    old "Kenji and Shizune meet in Hisao's room. Miraculously, nothing explodes."
    new "Kenji e Shizune se encontram no quarto de Hisao. Miraculosamente, nada explode."

    # game/definitions.rpy:224
    old "Succession"
    new "Sucessão"

    # game/definitions.rpy:224
    old "The current Student Council shapes up their successors before engaging in “extracurricular activities.”"
    new "O Conselho Estudantil atual analisa seus sucessores antes de fazerem “atividades extracurriculares”."

    # game/definitions.rpy:224
    old "Sneaking Mission"
    new "Missão Furtiva"

    # game/definitions.rpy:224
    old "The show of Misha's determination spurs Shizune to set her sights on greater things."
    new "A mostra da determinação de Misha faz Shizune focar sua visão em coisas maiores."

    # game/definitions.rpy:224
    old "Infinity"
    new "Infinito"

    # game/definitions.rpy:224
    old "Our trio renews their friendship, with their graduation looming close ahead."
    new "Nosso trio renova sua amizade, com a graduação deles se aproximando."

    # game/definitions.rpy:224
    old "Present Tense"
    new "Tempo Presente"

    # game/definitions.rpy:224
    old "Hisao stumbles into Lilly at lunch, and the two talk about Shizune."
    new "Hisao se encontra com Lilly no almoço, e os dois falam sobre a Shizune."

    # game/definitions.rpy:224
    old "Spiral"
    new "Espiral"

    # game/definitions.rpy:224
    old "Runaround, stonewalling, and Kenji nighttime ambush."
    new "Evasões, obstruções e uma emboscada noturna de Kenji."

    # game/definitions.rpy:224
    old "Terminal"
    new "Terminal"

    # game/definitions.rpy:224
    old "An early-morning talk with Shizune in the silent school."
    new "Uma conversa matinal com Shizune na escola silenciosa."

    # game/definitions.rpy:602
    old "“"
    new "“"

    # game/definitions.rpy:602
    old "”"
    new "”"

    # game/definitions.rpy:605
    old "Hisao"
    new "Hisao"

    # game/definitions.rpy:611
    old "Misha"
    new "Misha"

    # game/definitions.rpy:612
    old "Kenji"
    new "Kenji"

    # game/definitions.rpy:613
    old "Mutou"
    new "Mutou"

    # game/definitions.rpy:614
    old "Nurse"
    new "Enfermeiro"

    # game/definitions.rpy:615
    old "Nomiya"
    new "Nomiya"

    # game/definitions.rpy:616
    old "Yuuko"
    new "Yuuko"

    # game/definitions.rpy:617
    old "Sae"
    new "Sae"

    # game/definitions.rpy:618
    old "Akira"
    new "Akira"

    # game/definitions.rpy:619
    old "Hideaki"
    new "Hideaki"

    # game/definitions.rpy:620
    old "Jigoro"
    new "Jigoro"

    # game/definitions.rpy:621
    old "Meiko"
    new "Meiko"

    # game/definitions.rpy:622
    old "Shopkeep"
    new "Vendedor"

    # game/definitions.rpy:623
    old "Miki"
    new "Miki"

    # game/definitions.rpy:626
    old "{s}Shizune{/s} Misha"
    new "{s}Shizune{/s} Misha"

    # game/definitions.rpy:633
    old "Purple-haired girl"
    new "Garota de cabelos roxos"

    # game/definitions.rpy:634
    old "Twintails girl"
    new "Garota de maria-chiquinha"

    # game/definitions.rpy:635
    old "Strange girl"
    new "Garota estranha"

    # game/definitions.rpy:636
    old "Wavy-haired girl"
    new "Garota de cabelos ondulados"

    # game/definitions.rpy:637
    old "Laughing girl"
    new "Garota risonha"

    # game/definitions.rpy:638
    old "Bespectacled hallmate"
    new "Cara de óculos"

    # game/definitions.rpy:639
    old "Tall man"
    new "Homem alto"

    # game/definitions.rpy:640
    old "Librarian"
    new "Bibliotecária"

    # game/definitions.rpy:641
    old "Silver-haired man"
    new "Homem de cabelos prateados"

    # game/definitions.rpy:642
    old "Gallery owner"
    new "Dona da galeria"

    # game/definitions.rpy:643
    old "Well-dressed person"
    new "Pessoa bem vestida"

    # game/definitions.rpy:644
    old "Smiling man"
    new "Homem sorridente"

    # game/definitions.rpy:645
    old "Huge man"
    new "Homem enorme"

    # game/definitions.rpy:646
    old "Slim girl"
    new "Garota magra"

    # game/definitions.rpy:647
    old "Woman with braid"
    new "Mulher com trança"

