# TODO: Translation updated at 2025-08-09 03:42
# Generated by Renquill

translate pt_br strings:

    # game/labels.rpy:294
    old "In honor of XPND.dev\nThe man, who united all of us,\nand whose journey ended here..."
    new "Em homenagem ao XPND.dev\nO homem que uniu todos nós,\ne cuja jornada terminou aqui..."

    # game/labels.rpy:300
    old "In honor of XPND.dev\nThe man, who united all of us,\nand whose journey ended here...\nand who will be in our {i}fleeting{/i} hearts forever..."
    new "Em homenagem a XPND.dev\nO homem que uniu todos nós,\ne cuja jornada terminou aqui...\ne que estará em nossos {i}fugazes{/i} corações para sempre..."

