# TODO: Translation updated at 2025-12-19 01:29
# Generated by Renquill

translate pt_br strings:

    # game/screens.rpy:119
    old "Yes"
    new "Yes"

    # game/screens.rpy:120
    old "No"
    new "Não"

    # game/screens.rpy:152
    old "Return"
    new "Retornar"

    # game/screens.rpy:154
    old "History"
    new "Histórico"

    # game/screens.rpy:156
    old "Skip"
    new "Pular"

    # game/screens.rpy:158
    old "Auto"
    new "Modo automático"

    # game/screens.rpy:160
    old "Options"
    new "Opções"

    # game/screens.rpy:162
    old "Accessibility"
    new "Acessibilidade"

    # game/screens.rpy:164
    old "Saves"
    new "Saves"

    # game/screens.rpy:167
    old "Mods"
    new "Mods"

    # game/screens.rpy:169
    old "Main menu"
    new "Menu principal"

    # game/screens.rpy:172
    old "Quit"
    new "Sair"

    # game/screens.rpy:174
    old "Playtime"
    new "Tempo de jogo"

    # game/screens.rpy:180
    old "Current scene"
    new "Cena atual"

    # game/screens.rpy:180
    old "Current track"
    new "Faixa atual"

    # game/screens.rpy:195
    old "Start"
    new "Novo jogo"

    # game/screens.rpy:199
    old "Extras"
    new "Extras"

    # game/screens.rpy:244
    old "Adult content is disabled."
    new "O conteúdo adulto foi desativado."

    # game/screens.rpy:246
    old "Adult content is enabled."
    new "O conteúdo adulto foi ativado."

    # game/screens.rpy:248
    old "Disable adult content"
    new "Desativar conteúdo adulto"

    # game/screens.rpy:251
    old "Fullscreen mode"
    new "Modo tela cheia"

    # game/screens.rpy:253
    old "Skip unread text"
    new "Pular texto não lido"

    # game/screens.rpy:255
    old "Skip after choices"
    new "Pular depois de escolhas"

    # game/screens.rpy:258
    old "Parallax"
    new "Paralaxe"

    # game/screens.rpy:261
    old "Discord activity"
    new "Integração no Discord"

    # game/screens.rpy:264
    old "Hardware cursor"
    new "Cursor do hardware"

    # game/screens.rpy:271
    old "Blinking arrow"
    new "Seta piscando"

    # game/screens.rpy:273
    old "Disable expression transitions"
    new "Desativar transições expressivas"

    # game/screens.rpy:283
    old "Text speed"
    new "Velocidade do texto"

    # game/screens.rpy:292
    old "Auto mode delay"
    new "Velocidade do modo automático"

    # game/screens.rpy:302
    old "Music volume"
    new "Volume da música"

    # game/screens.rpy:312
    old "SFX volume"
    new "Volume do aúdio"

    # game/screens.rpy:316
    old "Test"
    new "Testar"

    # game/screens.rpy:320
    old "Language selection..."
    new "Seleção de idioma..."

    # game/screens.rpy:346
    old "Options > Language"
    new "Opções > Idiomas"

    # game/screens.rpy:357
    old "English"
    new "Inglês"

    # game/screens.rpy:358
    old "Russian"
    new "Russo"

    # game/screens.rpy:359
    old "French"
    new "Françês"

    # game/screens.rpy:360
    old "Italian"
    new "Italiano"

    # game/screens.rpy:361
    old "Spanish"
    new "Espanhol"

    # game/screens.rpy:362
    old "German"
    new "Alemão"

    # game/screens.rpy:363
    old "Japanese"
    new "Japonês"

    # game/screens.rpy:364
    old "Simplified Chinese"
    new "Chinês Simplificado"

    # game/screens.rpy:365
    old "Traditional Chinese"
    new "Chinês Tradicional"

    # game/screens.rpy:433
    old "Are you sure you want to\nload this save?"
    new "Tem certeza que deseja\ncarregar este arquivo?"

    # game/screens.rpy:455
    old "Scene"
    new "Cena"

    # game/screens.rpy:467
    old "Are you sure you want to\ndelete this save?"
    new "Tem certeza que deseja\ndeletar este arquivo?"

    # game/screens.rpy:478
    old "Save"
    new "Salvar"

    # game/screens.rpy:530
    old "Jukebox"
    new "Vitrola"

    # game/screens.rpy:551
    old "Gallery"
    new "Galeria"

    # game/screens.rpy:572
    old "Library"
    new "Biblioteca"

    # game/screens.rpy:593
    old "Cinema"
    new "Cinema"

    # game/screens.rpy:647
    old "Extras > Jukebox"
    new "Extras > Vitrola"

    # game/screens.rpy:651
    old "Now playing"
    new "Tocando"

    # game/screens.rpy:685
    old "Vol."
    new "Vol."

    # game/screens.rpy:687
    old "Stop"
    new "Parar"

    # game/screens.rpy:717
    old "Extras > Gallery"
    new "Extras > Galeria"

    # game/screens.rpy:767
    old "Page:"
    new "Página:"

    # game/screens.rpy:801
    old "Extras > Library"
    new "Extras > Biblioteca"

    # game/screens.rpy:857
    old "Completion: [completion_percentage]"
    new "Progresso: [completion_percentage]"



    # game/screens.rpy:888
    old "Extras > Cinema"
    new "Extras > Cinema"



    # game/screens.rpy:1033
    old "Fonts"
    new "Fontes"

    # game/screens.rpy:1040
    old "Default"
    new "Padrão"

    # game/screens.rpy:1047
    old "High contrast"
    new "Alto contraste"

    # game/screens.rpy:1050
    old "Self-voicing"
    new "Leitor de tela"

    # game/screens.rpy:1057
    old "Enable"
    new "Ativar"

    # game/screens.rpy:1067
    old "Volume drop"
    new "Volume do jogo"

    # game/screens.rpy:1069
    old "Mental health"
    new "Saúde mental"

    # game/screens.rpy:1076
    old "Skip hurtful adult scenes"
    new "Pular cenas adultas desagradáveis"

    # game/screens.rpy:1078
    old "Colorblind filter"
    new "Filtro daltônico"

    # game/screens.rpy:1177
    old "You must be 18+ to see adult content within this game.\nDo you meet these requirements?"
    new "Você deve ter mais de 18 anos para ver o conteúdo adulto neste jogo.\nVocê atende a esse requisito?"

    # game/screens.rpy:1178
    old "Note: answering \"No\" does NOT prevent you from playing the game."
    new "Observação: Responder \"Não\"  NÃO impede que você jogue o jogo."

    # game/screens.rpy:1179
    old "This question will not be shown again after you start playing."
    new "Essa pergunta não será feita novamente depois que você começar a jogar."

    # game/screens.rpy:362
    old "Brazilian Portuguese"
    new "Português Brasileiro"



