[tasks]
# no-op

[build]
  pc = false  # Windows + Linux
  win = false # Windows
  linux = true # Linux
  mac = false # macOS
  web = false # Web
  steam = false # Steam
  market = false # Multiple Markets (i.e. Itch.io)
  android_apk = false # Android Universal APK
  android_aab = false # Android Play Store Bundle

[renutil]
  version = "RENPY_VERSION" # the Ren'Py version to use (required)
  update_pickle = true
