# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# the less we use this, the better
transform show_lowres_fullscreen:
    xysize (1920, 1080)
    fit "contain"

image bg splash = image_fullpath("ui/splash.png")

image bg cake = image_fullpath("backgrounds/kurisumasu_keiki.png")
image bg city_karaokeint = image_fullpath("backgrounds/city_karaokeint.png")
image bg school_gardens3 = image_fullpath("backgrounds/school_gardens3.png")
image bg suburb_shanghaiext_ss = image_fullpath("backgrounds/suburb_shanghaiext_ss.png")

image act1card = show_lowres_fullscreen(image_fullpath("ui/act1card.png"))
image act1 = show_lowres_fullscreen(image_fullpath("ui/act1.png"))
image neutral = show_lowres_fullscreen(image_fullpath("ui/neutral.png"))
image act2suzu = show_lowres_fullscreen(image_fullpath("ui/act2suzu.png"))
image act2hisao =show_lowres_fullscreen(image_fullpath("ui/act2hisao.png"))

define passingact = ImageDissolve(Composite((1920, 1080), (650, 300), image_fullpath("ui/tr-tcard-act1.png")), 3.0)
define passingactsuzu = ImageDissolve(show_lowres_fullscreen(image_fullpath("ui/tc-act2suzu.png")), 3.0)
define passingacthisao = ImageDissolve(show_lowres_fullscreen(image_fullpath("ui/tc-act2hisao.png")), 3.0)

image kslogowords = image_fullpath("ui/kslogowords.png")
image kslogoheart = image_fullpath("ui/kslogoheart.png")
image solid_black = Solid("#000000")

# sprites: Aoi
image aoi_smile = show_lowres_fullscreen(image_fullpath("sprites/aoi_smile.png"))
image aoi_surprised = show_lowres_fullscreen(image_fullpath("sprites/aoi_surprised.png"))

# sprites: Haru
image haru_annoyed = show_lowres_fullscreen(image_fullpath("sprites/haru_annoyed.png"))
image haru_basic = show_lowres_fullscreen(image_fullpath("sprites/haru_basic.png"))
image haru_conehead = show_lowres_fullscreen(image_fullpath("sprites/haru_conehead.png"))
image haru_sad = show_lowres_fullscreen(image_fullpath("sprites/haru_sad.png"))
image haru_serious = show_lowres_fullscreen(image_fullpath("sprites/haru_serious.png"))
image haru_smile = show_lowres_fullscreen(image_fullpath("sprites/haru_smile.png"))
image haru_yo = show_lowres_fullscreen(image_fullpath("sprites/haru_yo.png"))

# sprites: Hisao
image hisao_blank = show_lowres_fullscreen(image_fullpath("sprites/hisao_blank.png"))
image hisao_erm = show_lowres_fullscreen(image_fullpath("sprites/hisao_erm.png"))
image hisao_erm_u = show_lowres_fullscreen(image_fullpath("sprites/hisao_erm_uniform.png"))
image hisao_talk_big = show_lowres_fullscreen(image_fullpath("sprites/hisao_talk_big.png"))
image hisao_talk_big_u = show_lowres_fullscreen(image_fullpath("sprites/hisao_talk_big_uniform.png"))
image hisao_smile = show_lowres_fullscreen(image_fullpath("sprites/hisao_smile.png"))
image hisao_smile_u = show_lowres_fullscreen(image_fullpath("sprites/hisao_smile_uniform.png"))
image hisao_wtf = show_lowres_fullscreen(image_fullpath("sprites/hisao_wtf.png"))
image hisao_wtf_u = show_lowres_fullscreen(image_fullpath("sprites/hisao_wtf_uniform.png"))
image hisao_biggrin = show_lowres_fullscreen(image_fullpath("sprites/hisao_biggrin.png"))
image hisao_biggrin_u = show_lowres_fullscreen(image_fullpath("sprites/hisao_biggrin_uniform.png"))
image hisao_disappoint = show_lowres_fullscreen(image_fullpath("sprites/hisao_disappoint.png"))
image hisao_disappoint_u = show_lowres_fullscreen(image_fullpath("sprites/hisao_disappoint_uniform.png"))
image hisao_frown = show_lowres_fullscreen(image_fullpath("sprites/hisao_frown.png"))
image hisao_frown_u = show_lowres_fullscreen(image_fullpath("sprites/hisao_frown_uniform.png"))
image hisao_heh = show_lowres_fullscreen(image_fullpath("sprites/hisao_heh.png"))
image hisao_heh_u = show_lowres_fullscreen(image_fullpath("sprites/hisao_heh_uniform.png"))
image hisao_smile_teeth = show_lowres_fullscreen(image_fullpath("sprites/hisao_smile_teeth.png"))
image hisao_smile_teeth_u = show_lowres_fullscreen(image_fullpath("sprites/hisao_smile_teeth_uniform.png"))
image hisao_talk_small = show_lowres_fullscreen(image_fullpath("sprites/hisao_talk_small.png"))
image hisao_talk_small_u = show_lowres_fullscreen(image_fullpath("sprites/hisao_talk_small_uniform.png"))
image hisao_hmpf = show_lowres_fullscreen(image_fullpath("sprites/hisao_hmpf.png"))
image hisao_hmpf_u = show_lowres_fullscreen(image_fullpath("sprites/hisao_hmpf_uniform.png"))
image hisao_closed = show_lowres_fullscreen(image_fullpath("sprites/hisao_closed.png"))
image hisao_closed_u = show_lowres_fullscreen(image_fullpath("sprites/hisao_closed_uniform.png"))
image hisao_declare = show_lowres_fullscreen(image_fullpath("sprites/hisao_declare.png"))
image hisao_declare_u = show_lowres_fullscreen(image_fullpath("sprites/hisao_declare_uniform.png"))
image hisao_blush = show_lowres_fullscreen(image_fullpath("sprites/hisao_blush.png"))
image hisao_blush_u = show_lowres_fullscreen(image_fullpath("sprites/hisao_blush_uniform.png"))
image hisao_beach_blush = show_lowres_fullscreen(image_fullpath("sprites/hisao_beach_blush.png"))
image hisao_beach_frown = show_lowres_fullscreen(image_fullpath("sprites/hisao_beach_frown.png"))
image hisao_beach_smile = show_lowres_fullscreen(image_fullpath("sprites/hisao_beach_smile.png"))
image hisao_beach_erm = show_lowres_fullscreen(image_fullpath("sprites/hisao_beach_erm.png"))
image hisao_beach_disappoint = show_lowres_fullscreen(image_fullpath("sprites/hisao_beach_disappoint.png"))
image hisao_beach_talk = show_lowres_fullscreen(image_fullpath("sprites/hisao_beach_talk.png"))
image hisao_beach_grin = show_lowres_fullscreen(image_fullpath("sprites/hisao_beach_grin.png"))
image hisao_beach_declare = show_lowres_fullscreen(image_fullpath("sprites/hisao_beach_declare.png"))
image hisao_topless = show_lowres_fullscreen(image_fullpath("sprites/hisao_topless.png"))
image hisao_pale = show_lowres_fullscreen(image_fullpath("sprites/hisao_pale.png"))
image hisao_wtf_close = show_lowres_fullscreen(image_fullpath("sprites/hisao_wtf_close.png"))
image hisao_wtf_close_u = show_lowres_fullscreen(image_fullpath("sprites/hisao_wtf_close_uniform.png"))
image hisao_erm_close = show_lowres_fullscreen(image_fullpath("sprites/hisao_erm_close.png"))
image hisao_erm_close_u = show_lowres_fullscreen(image_fullpath("sprites/hisao_erm_close_uniform.png"))
image hisao_smile_close = show_lowres_fullscreen(image_fullpath("sprites/hisao_smile_close.png"))
image hisao_smile_close_u = show_lowres_fullscreen(image_fullpath("sprites/hisao_smile_close_uniform.png"))
image hisao_topless_smile = show_lowres_fullscreen(image_fullpath("sprites/hisao_topless_smile.png"))

# sprites: Saki
image saki = show_lowres_fullscreen(image_fullpath("sprites/saki.png"))
image saki_frown = show_lowres_fullscreen(image_fullpath("sprites/saki_frown.png"))

# sprites: Snoozu
image suzu_angry = show_lowres_fullscreen(image_fullpath("sprites/suzu_angry.png"))
image suzu_angry_d = show_lowres_fullscreen(image_fullpath("sprites/suzu_angry_dress.png"))
image suzu_concerned = show_lowres_fullscreen(image_fullpath("sprites/suzu_concerned.png"))
image suzu_concerned_d = show_lowres_fullscreen(image_fullpath("sprites/suzu_concerned_dress.png"))
image suzu_embarrassed = show_lowres_fullscreen(image_fullpath("sprites/suzu_embarrassed.png"))
image suzu_embarrassed_d = show_lowres_fullscreen(image_fullpath("sprites/suzu_embarrassed_dress.png"))
image suzu_grin = show_lowres_fullscreen(image_fullpath("sprites/suzu_grin.png"))
image suzu_grin_d = show_lowres_fullscreen(image_fullpath("sprites/suzu_grin_dress.png"))
image suzu_happy = show_lowres_fullscreen(image_fullpath("sprites/suzu_happy.png"))
image suzu_happy_d = show_lowres_fullscreen(image_fullpath("sprites/suzu_happy_dress.png"))
image suzu_invis = show_lowres_fullscreen(image_fullpath("sprites/suzu_invis.png"))
image suzu_normal = show_lowres_fullscreen(image_fullpath("sprites/suzu_normal.png"))
image suzu_normal_d = show_lowres_fullscreen(image_fullpath("sprites/suzu_normal_dress.png"))
image suzu_side = show_lowres_fullscreen(image_fullpath("sprites/suzu_side.png"))
image suzu_smile = show_lowres_fullscreen(image_fullpath("sprites/suzu_smile.png"))
image suzu_smile_d = show_lowres_fullscreen(image_fullpath("sprites/suzu_smile_dress.png"))
image suzu_speak = show_lowres_fullscreen(image_fullpath("sprites/suzu_speak.png"))
image suzu_speak_d = show_lowres_fullscreen(image_fullpath("sprites/suzu_speak_dress.png"))
image suzu_speak_close = show_lowres_fullscreen(image_fullpath("sprites/suzu_speak_close.png"))
image suzu_speak_close_d = show_lowres_fullscreen(image_fullpath("sprites/suzu_speak_close_dress.png"))
image suzu_surprised = show_lowres_fullscreen(image_fullpath("sprites/suzu_surprised.png"))
image suzu_surprised_d = show_lowres_fullscreen(image_fullpath("sprites/suzu_surprised_dress.png"))
image suzu_veryangry = show_lowres_fullscreen(image_fullpath("sprites/suzu_veryangry.png"))
image suzu_veryangry_d = show_lowres_fullscreen(image_fullpath("sprites/suzu_veryangry_dress.png"))
image suzu_unhappy = show_lowres_fullscreen(image_fullpath("sprites/suzu_unhappy.png"))
image suzu_unhappy_d = show_lowres_fullscreen(image_fullpath("sprites/suzu_unhappy_dress.png"))
image suzu_sleepy = show_lowres_fullscreen(image_fullpath("sprites/suzu_sleepy.png"))
image suzu_sleepy_d = show_lowres_fullscreen(image_fullpath("sprites/suzu_sleepy_dress.png"))
image suzu_asleep = show_lowres_fullscreen(image_fullpath("sprites/suzu_asleep.png"))
image suzu_asleep_d = show_lowres_fullscreen(image_fullpath("sprites/suzu_asleep_dress.png"))
image suzu_veryembarrassed = show_lowres_fullscreen(image_fullpath("sprites/suzu_veryembarrassed.png"))
image suzu_veryembarrassed_d = show_lowres_fullscreen(image_fullpath("sprites/suzu_veryembarrassed_dress.png"))
image suzu_beach_normal = show_lowres_fullscreen(image_fullpath("sprites/suzu_beach_normal.png"))
image suzu_beach_annoyed = show_lowres_fullscreen(image_fullpath("sprites/suzu_beach_annoyed.png"))
image suzu_beach_angry = show_lowres_fullscreen(image_fullpath("sprites/suzu_beach_angry.png"))
image suzu_beach_smile = show_lowres_fullscreen(image_fullpath("sprites/suzu_beach_smile.png"))
image suzu_beach_small_em = show_lowres_fullscreen(image_fullpath("sprites/suzu_beach_small_em.png"))
image suzu_beach_sad = show_lowres_fullscreen(image_fullpath("sprites/suzu_beach_sad.png"))
image suzu_beach_surprised = show_lowres_fullscreen(image_fullpath("sprites/suzu_beach_surprised.png"))
image suzu_cry = show_lowres_fullscreen(image_fullpath("sprites/suzu_cry.png"))
image suzu_cry_d = show_lowres_fullscreen(image_fullpath("sprites/suzu_cry_dress.png"))
image suzu_cry_smile = show_lowres_fullscreen(image_fullpath("sprites/suzu_cry_smile.png"))
image suzu_cry_smile_d = show_lowres_fullscreen(image_fullpath("sprites/suzu_cry_smile_dress.png"))
image suzu_despair = show_lowres_fullscreen(image_fullpath("sprites/suzu_despair.png"))
image suzu_despair_d = show_lowres_fullscreen(image_fullpath("sprites/suzu_despair_dress.png"))
image suzu_neutral = show_lowres_fullscreen(image_fullpath("sprites/suzu_neutral.png"))
image suzu_neutral_d = show_lowres_fullscreen(image_fullpath("sprites/suzu_neutral_dress.png"))
image suzu_glare = show_lowres_fullscreen(image_fullpath("sprites/suzu_glare.png"))
image suzu_glare_d = show_lowres_fullscreen(image_fullpath("sprites/suzu_glare_dress.png"))

# sprites: Mr. Suzuki
image suzu_father_happy = show_lowres_fullscreen(image_fullpath("sprites/suzu_father_happy.png"))
image suzu_father_unhappy = show_lowres_fullscreen(image_fullpath("sprites/suzu_father_unhappy.png"))
image suzu_father_normal = show_lowres_fullscreen(image_fullpath("sprites/suzu_father_normal.png"))
image suzu_father_shock = show_lowres_fullscreen(image_fullpath("sprites/suzu_father_shock.png"))

# sprites: Yukio
image yukio_angry = show_lowres_fullscreen(image_fullpath("sprites/yukio_angry.png"))
image yukio_blush = show_lowres_fullscreen(image_fullpath("sprites/yukio_blush.png"))
image yukio_eeh = show_lowres_fullscreen(image_fullpath("sprites/yukio_eeh.png"))
image yukio_huh = show_lowres_fullscreen(image_fullpath("sprites/yukio_huh.png"))
image yukio_notimpressed = show_lowres_fullscreen(image_fullpath("sprites/yukio_notimpressed.png"))
image yukio_smile = show_lowres_fullscreen(image_fullpath("sprites/yukio_smile.png"))
image yukio_punched = show_lowres_fullscreen(image_fullpath("sprites/yukio_punched.png"))
image yukio_punched_defiant = show_lowres_fullscreen(image_fullpath("sprites/yukio_punched_defiant.png"))
image yukio_punched_angry = show_lowres_fullscreen(image_fullpath("sprites/yukio_punched_angry.png"))
