name: Download artifact from SSH storage
description: This snippet downloads named artifact from SSH storage.

inputs:
  ssh_host:
    required: true
  ssh_port:
    required: true
  ssh_user:
    required: true
  ssh_key:
    required: true
  storage_prefix:
    required: true
  directory:
    required: true
  artifact_name:
    required: true

runs:
  using: "composite"
  steps:
    - name: Download artifact
      id: download-artifact
      run: |
        set -euo pipefail

        eval $(ssh-agent -s)
        echo "${{ inputs.ssh_key }}" | base64 -d | ssh-add -

        mkdir -p ~/.ssh && echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
        chmod 600 ~/.ssh/config

        mkdir -p ./dists/
        scp -P ${{ inputs.ssh_port }} "${{ inputs.ssh_user }}@${{ inputs.ssh_host }}:${{ inputs.storage_prefix }}/${{ inputs.directory }}/${{ inputs.artifact_name }}" ./dists/
