when:
  event: push

depends_on:
  - build

labels:
  platform: linux/amd64 # it doesn't build on arm64, unfortuantely

steps:
  prepare-env:
    image: alpine:latest
    commands:
      - apk update && apk add git
      - chmod +x ./scripts/*.sh
      - ./scripts/prepare_env.sh

  build:
    image: debian:latest
    commands:
      - export $(grep -v '^#' .env | xargs)
      - sed -i "s#TARBALL_DIR#/data/$${CI_PRETTY_VERSION}#" ./scripts/appimage.sh
      - apt update && apt install wget
      - ./scripts/appimage.sh
      - cp -v ./dists/sh.fhs.ksre-x86_64.AppImage /data/$${CI_PRETTY_VERSION}/
    when:
      event: push
    volumes:
      - "/data/ci:/data"
    depends_on:
      - prepare-env
