when:
  event: push

depends_on:
  - lint

labels:
  platform: linux/arm64

steps:
  prepare-env:
    image: alpine:latest
    commands:
      - apk update && apk add git
      - chmod +x ./scripts/*.sh
      - ./scripts/prepare_env.sh

  build:
    image: source.hodakov.me/containers/renkit:latest
    environment:
      SDL_AUDIODRIVER: dummy
      SDL_VIDEODRIVER: dummy
      RENPY_VERSION: 8.3.7
      KEYSTORE_APK:
        from_secret: keystore_apk
      KEYSTORE_PASS:
        from_secret: keystore_pass
    commands:
      - export $(grep -v '^#' .env | xargs)
      - mkdir ./dists /data/$${CI_PRETTY_VERSION}/
      - sed -i "s#v0.0.0-localbuild#$${CI_KSRE_VERSION}#" game/config.rpy
      - sed -i "s#KEYSTORE_APK#$${KEYSTORE_APK}#" renconstruct.toml
      - sed -i "s#KEYSTORE_ALIAS#$${KEYSTORE_ALIAS}#" renconstruct.toml
      - sed -i "s#KEYSTORE_PASS#$${KEYSTORE_PASS}#" renconstruct.toml
      - sed -i "s#RENPY_VERSION#$${RENPY_VERSION}#" renconstruct.toml
      - renconstruct build -c renconstruct.toml . ./dists
      - cp -Rv ./dists/* /data/$${CI_PRETTY_VERSION}/
    when:
      event: push
    volumes:
      - "/data/ci:/data"
    depends_on:
      - prepare-env
