when:
  event: push

labels:
  platform: linux/amd64 # it doesn't build on arm64, unfortuantely

steps:
  build:
    image: source.hodakov.me/containers/renkit:latest
    environment:
      SDL_AUDIODRIVER: dummy
      SDL_VIDEODRIVER: dummy
      RENPY_VERSION: 8.3.7
      KEYSTORE_APK:
        from_secret: keystore_apk
      KEYSTORE_PASS:
        from_secret: keystore_pass
    commands:
      - chmod +x ./scripts
      - ./scripts/prepare_env.sh
      - source .env
      - mkdir ./dists /data/${CI_COMMIT_SHA:0:10}/
      - sed -i "s#KEYSTORE_APK#$${KEYSTORE_APK}#" renconstruct.toml
      - sed -i "s#KEYSTORE_ALIAS#$${KEYSTORE_ALIAS}#" renconstruct.toml
      - sed -i "s#KEYSTORE_PASS#$${KEYSTORE_PASS}#" renconstruct.toml
      - sed -i "s#RENPY_VERSION#$${RENPY_VERSION}#" renconstruct.toml
      - renconstruct build -c renconstruct.toml . ./dists
      - cp -Rv ./dists/* /data/${CI_COMMIT_SHA:0:10}/
    when:
      event: push
    volumes:
      - "/data/ci/:/data"
    entrypoint: ["/bin/bash", "-c", "echo $CI_SCRIPT | base64 -d | /bin/bash -e"]
