matrix:
  platform:
    - linux/amd64
    - linux/arm64

labels:
  platform: ${platform}

when:
  event: push

steps:
  build:
    image: source.hodakov.me/containers/renkit:latest
    environment:
      SDL_AUDIODRIVER: dummy
      SDL_VIDEODRIVER: dummy
      RENPY_VERSION: 8.3.7
    commands:
      - mkdir ./dists
      - echo ${RENPY_VERSION}
      - sed -i 's#RENPY_VERSION#$${RENPY_VERSION}#' renconstruct/linux.toml
      - renconstruct build -c renconstruct/linux.toml . ./dists
      - ls -lah # check files
    when:
      event: push
