matrix:
  platform:
    - linux/amd64
    - linux/arm64

labels:
  platform: ${platform}

when:
  event: push

steps:
  build:
    image: source.hodakov.me/containers/renkit:latest
    commands:
      - mkdir ./dists
      - source renconstruct/.env
      - sed -i 's#RENPY_VERSION#${RENPY_VERSION}#' renconstruct/linux.toml
      - renconstruct build -c renconstruct/linux.toml . ./dists
      - ls -lah # check files
    when:
      event: push
